// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package security

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AzureResourceEntityMapping struct {
    EntityMapping
}
// NewAzureResourceEntityMapping instantiates a new AzureResourceEntityMapping and sets the default values.
func NewAzureResourceEntityMapping()(*AzureResourceEntityMapping) {
    m := &AzureResourceEntityMapping{
        EntityMapping: *NewEntityMapping(),
    }
    odataTypeValue := "#microsoft.graph.security.azureResourceEntityMapping"
    m.SetOdataType(&odataTypeValue)
    return m
}
// CreateAzureResourceEntityMappingFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAzureResourceEntityMappingFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAzureResourceEntityMapping(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AzureResourceEntityMapping) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.EntityMapping.GetFieldDeserializers()
    res["resourceIdColumn"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetResourceIdColumn(val)
        }
        return nil
    }
    return res
}
// GetResourceIdColumn gets the resourceIdColumn property value. Name of the detection query column that maps to the resource ID of the alert entity.
// returns a *string when successful
func (m *AzureResourceEntityMapping) GetResourceIdColumn()(*string) {
    val, err := m.GetBackingStore().Get("resourceIdColumn")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// Serialize serializes information the current object
func (m *AzureResourceEntityMapping) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.EntityMapping.Serialize(writer)
    if err != nil {
        return err
    }
    {
        err = writer.WriteStringValue("resourceIdColumn", m.GetResourceIdColumn())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetResourceIdColumn sets the resourceIdColumn property value. Name of the detection query column that maps to the resource ID of the alert entity.
func (m *AzureResourceEntityMapping) SetResourceIdColumn(value *string)() {
    err := m.GetBackingStore().Set("resourceIdColumn", value)
    if err != nil {
        panic(err)
    }
}
type AzureResourceEntityMappingable interface {
    EntityMappingable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetResourceIdColumn()(*string)
    SetResourceIdColumn(value *string)()
}
