package teamtemplatedefinition

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaGetResponseable instead.
type ItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaResponse struct {
    ItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaGetResponse
}
// NewItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaResponse instantiates a new ItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaResponse and sets the default values.
func NewItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaResponse()(*ItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaResponse) {
    m := &ItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaResponse{
        ItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaGetResponse: *NewItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaGetResponse(),
    }
    return m
}
// CreateItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaGetResponseable instead.
type ItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaResponseable interface {
    ItemTeamDefinitionChannelsItemPlannerPlansItemBucketsItemTasksDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
