package teamtemplatedefinition

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse 
// Deprecated: This class is obsolete. Use checkMemberGroupsPostResponse instead.
type ItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse struct {
    ItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsPostResponse
}
// NewItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse instantiates a new ItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse and sets the default values.
func NewItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse()(*ItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse) {
    m := &ItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse{
        ItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsPostResponse: *NewItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsPostResponse(),
    }
    return m
}
// CreateItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse(), nil
}
// ItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponseable 
// Deprecated: This class is obsolete. Use checkMemberGroupsPostResponse instead.
type ItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponseable interface {
    ItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
