package teamtemplatedefinition

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponse 
// Deprecated: This class is obsolete. Use checkMemberObjectsPostResponse instead.
type ItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponse struct {
    ItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsPostResponse
}
// NewItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponse instantiates a new ItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponse and sets the default values.
func NewItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponse()(*ItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponse) {
    m := &ItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponse{
        ItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsPostResponse: *NewItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsPostResponse(),
    }
    return m
}
// CreateItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponse(), nil
}
// ItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponseable 
// Deprecated: This class is obsolete. Use checkMemberObjectsPostResponse instead.
type ItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsResponseable interface {
    ItemTeamDefinitionPermissionGrantsItemCheckMemberObjectsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
