package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponseable instead.
type EnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse struct {
    EnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponse
}
// NewEnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse instantiates a new EnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse and sets the default values.
func NewEnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse()(*EnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse) {
    m := &EnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse{
        EnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponse: *NewEnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateEnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use EnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponseable instead.
type EnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponseable interface {
    EnterpriseAppsItemRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
