package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type EnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    EnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewEnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new EnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewEnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*EnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &EnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        EnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewEnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateEnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use EnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type EnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    EnterpriseappsItemRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
