package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type EnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    EnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewEnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new EnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewEnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*EnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &EnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        EnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewEnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateEnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use EnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type EnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    EnterpriseappsItemRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
