package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// EnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type EnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse struct {
    EnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnGetResponse
}
// NewEnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse instantiates a new EnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse and sets the default values.
func NewEnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse()(*EnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse) {
    m := &EnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse{
        EnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnGetResponse: *NewEnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateEnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateEnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse(), nil
}
// EnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponseable 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type EnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnResponseable interface {
    EnterpriseAppsItemRoleAssignmentApprovalsFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
