package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnGetResponseable instead.
type EnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse struct {
    EnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnGetResponse
}
// NewEnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse instantiates a new EnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse and sets the default values.
func NewEnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse()(*EnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse) {
    m := &EnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse{
        EnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnGetResponse: *NewEnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateEnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use EnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnGetResponseable instead.
type EnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnResponseable interface {
    EnterpriseAppsItemRoleAssignmentSchedulesFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
