package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use {TypeName} instead.
type EntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse struct {
    EntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnGetResponse
}
// NewEntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse instantiates a new EntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse and sets the default values.
func NewEntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse()(*EntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse) {
    m := &EntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse{
        EntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnGetResponse: *NewEntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateEntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use {TypeName} instead.
type EntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnResponseable interface {
    EntitlementManagementRoleAssignmentApprovalsFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
