package reports

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodGetResponseable instead.
type GetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodResponse struct {
    GetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodGetResponse
}
// NewGetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodResponse instantiates a new GetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodResponse and sets the default values.
func NewGetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodResponse()(*GetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodResponse) {
    m := &GetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodResponse{
        GetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodGetResponse: *NewGetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodGetResponse(),
    }
    return m
}
// CreateGetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodResponse(), nil
}
// Deprecated: This class is obsolete. Use GetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodGetResponseable instead.
type GetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodResponseable interface {
    GetazureadapplicationsigninsummarywithperiodGetAzureADApplicationSignInSummaryWithPeriodGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
