package reports

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodGetResponseable instead.
type GetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodResponse struct {
    GetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodGetResponse
}
// NewGetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodResponse instantiates a new GetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodResponse and sets the default values.
func NewGetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodResponse()(*GetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodResponse) {
    m := &GetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodResponse{
        GetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodGetResponse: *NewGetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodGetResponse(),
    }
    return m
}
// CreateGetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodResponse(), nil
}
// Deprecated: This class is obsolete. Use GetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodGetResponseable instead.
type GetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodResponseable interface {
    GetcredentialusagesummarywithperiodGetCredentialUsageSummaryWithPeriodGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
