package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponse 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type AccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponse struct {
    AccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnGetResponse
}
// NewAccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponse instantiates a new AccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponse and sets the default values.
func NewAccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponse()(*AccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponse) {
    m := &AccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponse{
        AccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnGetResponse: *NewAccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateAccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateAccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponse(), nil
}
// AccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponseable 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type AccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnResponseable interface {
    AccessReviewsDecisionsItemInstanceStagesItemDecisionsFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
