package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type AccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    AccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewAccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new AccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewAccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*AccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &AccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        AccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewAccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateAccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use AccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type AccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    AccessreviewsDefinitionsItemInstancesItemStagesItemDecisionsItemInstanceDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
