package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsPostResponseable instead.
type EntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsResponse struct {
    EntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsPostResponse
}
// NewEntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsResponse instantiates a new EntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsResponse and sets the default values.
func NewEntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsResponse()(*EntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsResponse) {
    m := &EntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsResponse{
        EntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsPostResponse: *NewEntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsPostResponse(),
    }
    return m
}
// CreateEntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsResponse(), nil
}
// Deprecated: This class is obsolete. Use EntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsPostResponseable instead.
type EntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsResponseable interface {
    EntitlementManagementAccessPackagesWithUniqueNameGetApplicablePolicyRequirementsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
