package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EntitlementmanagementAccesspackageassignmentresourcerolesMyGetResponseable instead.
type EntitlementmanagementAccesspackageassignmentresourcerolesMyResponse struct {
    EntitlementmanagementAccesspackageassignmentresourcerolesMyGetResponse
}
// NewEntitlementmanagementAccesspackageassignmentresourcerolesMyResponse instantiates a new EntitlementmanagementAccesspackageassignmentresourcerolesMyResponse and sets the default values.
func NewEntitlementmanagementAccesspackageassignmentresourcerolesMyResponse()(*EntitlementmanagementAccesspackageassignmentresourcerolesMyResponse) {
    m := &EntitlementmanagementAccesspackageassignmentresourcerolesMyResponse{
        EntitlementmanagementAccesspackageassignmentresourcerolesMyGetResponse: *NewEntitlementmanagementAccesspackageassignmentresourcerolesMyGetResponse(),
    }
    return m
}
// CreateEntitlementmanagementAccesspackageassignmentresourcerolesMyResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEntitlementmanagementAccesspackageassignmentresourcerolesMyResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementmanagementAccesspackageassignmentresourcerolesMyResponse(), nil
}
// Deprecated: This class is obsolete. Use EntitlementmanagementAccesspackageassignmentresourcerolesMyGetResponseable instead.
type EntitlementmanagementAccesspackageassignmentresourcerolesMyResponseable interface {
    EntitlementmanagementAccesspackageassignmentresourcerolesMyGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
