package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// EntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponse 
// Deprecated: This class is obsolete. Use MyGetResponse instead.
type EntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponse struct {
    EntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyGetResponse
}
// NewEntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponse instantiates a new EntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponse and sets the default values.
func NewEntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponse()(*EntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponse) {
    m := &EntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponse{
        EntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyGetResponse: *NewEntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyGetResponse(),
    }
    return m
}
// CreateEntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateEntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponse(), nil
}
// EntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponseable 
// Deprecated: This class is obsolete. Use MyGetResponse instead.
type EntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyResponseable interface {
    EntitlementManagementAccessPackageAssignmentsItemAccessPackageAssignmentResourceRolesMyGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
