package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use PermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    PermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewPermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new PermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewPermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*PermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &PermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        PermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewPermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreatePermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use PermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PermissionsmanagementScheduledpermissionsapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
}
