package networkaccess

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetResponseable instead.
type AlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeResponse struct {
    AlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetResponse
}
// NewAlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeResponse instantiates a new AlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeResponse and sets the default values.
func NewAlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeResponse()(*AlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeResponse) {
    m := &AlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeResponse{
        AlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetResponse: *NewAlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetResponse(),
    }
    return m
}
// CreateAlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeResponse(), nil
}
// Deprecated: This class is obsolete. Use AlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetResponseable instead.
type AlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeResponseable interface {
    AlertsMicrosoftGraphNetworkaccessGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetAlertSeveritySummariesWithStartDateTimeWithEndDateTimeGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
