package networkaccess

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeGetResponseable instead.
type ReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeResponse struct {
    ReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeGetResponse
}
// NewReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeResponse instantiates a new ReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeResponse and sets the default values.
func NewReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeResponse()(*ReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeResponse) {
    m := &ReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeResponse{
        ReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeGetResponse: *NewReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeGetResponse(),
    }
    return m
}
// CreateReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeResponse(), nil
}
// Deprecated: This class is obsolete. Use ReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeGetResponseable instead.
type ReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    ReportsMicrosoftgraphnetworkaccesswebcategoryreportwithstartdatetimewithenddatetimeWebCategoryReportWithStartDateTimeWithEndDateTimeGetResponseable
}
