package networkaccess

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponse 
// Deprecated: This class is obsolete. Use getDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetResponse instead.
type ReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponse struct {
    ReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetResponse
}
// NewReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponse instantiates a new ReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponse and sets the default values.
func NewReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponse()(*ReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponse) {
    m := &ReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponse{
        ReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetResponse: *NewReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetResponse(),
    }
    return m
}
// CreateReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponse(), nil
}
// ReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponseable 
// Deprecated: This class is obsolete. Use getDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetResponse instead.
type ReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    ReportsMicrosoftGraphNetworkaccessGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetDiscoveredApplicationSegmentReportWithStartDateTimeWithEndDateTimeGetResponseable
}
