package networkaccess

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponse 
// Deprecated: This class is obsolete. Use destinationReportWithStartDateTimeWithEndDateTimeGetResponse instead.
type ReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponse struct {
    ReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeGetResponse
}
// NewReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponse instantiates a new ReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponse and sets the default values.
func NewReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponse()(*ReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponse) {
    m := &ReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponse{
        ReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeGetResponse: *NewReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeGetResponse(),
    }
    return m
}
// CreateReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponse(), nil
}
// ReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponseable 
// Deprecated: This class is obsolete. Use destinationReportWithStartDateTimeWithEndDateTimeGetResponse instead.
type ReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    ReportsMicrosoftGraphNetworkaccessDestinationReportWithStartDateTimeWithEndDateTimeDestinationReportWithStartDateTimeWithEndDateTimeGetResponseable
}
