package networkaccess

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponse 
// Deprecated: This class is obsolete. Use entitiesSummariesWithStartDateTimeWithEndDateTimeGetResponse instead.
type ReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponse struct {
    ReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeGetResponse
}
// NewReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponse instantiates a new ReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponse and sets the default values.
func NewReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponse()(*ReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponse) {
    m := &ReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponse{
        ReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeGetResponse: *NewReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeGetResponse(),
    }
    return m
}
// CreateReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponse(), nil
}
// ReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponseable 
// Deprecated: This class is obsolete. Use entitiesSummariesWithStartDateTimeWithEndDateTimeGetResponse instead.
type ReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    ReportsMicrosoftGraphNetworkaccessEntitiesSummariesWithStartDateTimeWithEndDateTimeEntitiesSummariesWithStartDateTimeWithEndDateTimeGetResponseable
}
