package networkaccess

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use {TypeName} instead.
type ReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByResponse struct {
    ReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetResponse
}
// NewReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByResponse instantiates a new ReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByResponse and sets the default values.
func NewReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByResponse()(*ReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByResponse) {
    m := &ReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByResponse{
        ReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetResponse: *NewReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetResponse(),
    }
    return m
}
// CreateReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByResponse(), nil
}
// Deprecated: This class is obsolete. Use {TypeName} instead.
type ReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    ReportsMicrosoftGraphNetworkaccessGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetDestinationSummariesWithStartDateTimeWithEndDateTimeWithAggregatedByGetResponseable
}
