package networkaccess

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeGetResponseable instead.
type ReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeResponse struct {
    ReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeGetResponse
}
// NewReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeResponse instantiates a new ReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeResponse and sets the default values.
func NewReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeResponse()(*ReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeResponse) {
    m := &ReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeResponse{
        ReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeGetResponse: *NewReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeGetResponse(),
    }
    return m
}
// CreateReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeResponse(), nil
}
// Deprecated: This class is obsolete. Use ReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeGetResponseable instead.
type ReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    ReportsMicrosoftgraphnetworkaccesscrosstenantaccessreportwithstartdatetimewithenddatetimeCrossTenantAccessReportWithStartDateTimeWithEndDateTimeGetResponseable
}
