package networkaccess

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponse 
// Deprecated: This class is obsolete. Use trafficDistributionWithStartDateTimeWithEndDateTimeGetResponse instead.
type ReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponse struct {
    ReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeGetResponse
}
// NewReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponse instantiates a new ReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponse and sets the default values.
func NewReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponse()(*ReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponse) {
    m := &ReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponse{
        ReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeGetResponse: *NewReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeGetResponse(),
    }
    return m
}
// CreateReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponse(), nil
}
// ReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponseable 
// Deprecated: This class is obsolete. Use trafficDistributionWithStartDateTimeWithEndDateTimeGetResponse instead.
type ReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    ReportsMicrosoftGraphNetworkaccessTrafficDistributionWithStartDateTimeWithEndDateTimeTrafficDistributionWithStartDateTimeWithEndDateTimeGetResponseable
}
