package security

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use TiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdPostResponseable instead.
type TiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdResponse struct {
    TiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdPostResponse
}
// NewTiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdResponse instantiates a new TiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdResponse and sets the default values.
func NewTiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdResponse()(*TiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdResponse) {
    m := &TiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdResponse{
        TiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdPostResponse: *NewTiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdPostResponse(),
    }
    return m
}
// CreateTiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdResponse(), nil
}
// Deprecated: This class is obsolete. Use TiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdPostResponseable instead.
type TiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TiindicatorsDeletetiindicatorsbyexternalidDeleteTiIndicatorsByExternalIdPostResponseable
}
