package monitoring

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponseable instead.
type AlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse struct {
    AlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponse
}
// NewAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse instantiates a new AlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse and sets the default values.
func NewAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse()(*AlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse) {
    m := &AlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse{
        AlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponse: *NewAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponse(),
    }
    return m
}
// CreateAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse(), nil
}
// Deprecated: This class is obsolete. Use AlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponseable instead.
type AlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponseable interface {
    AlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
