package monitoring

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponse 
// Deprecated: This class is obsolete. Use getPortalNotificationsGetResponse instead.
type AlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponse struct {
    AlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsGetResponse
}
// NewAlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponse instantiates a new AlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponse and sets the default values.
func NewAlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponse()(*AlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponse) {
    m := &AlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponse{
        AlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsGetResponse: *NewAlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsGetResponse(),
    }
    return m
}
// CreateAlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateAlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponse(), nil
}
// AlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponseable 
// Deprecated: This class is obsolete. Use getPortalNotificationsGetResponse instead.
type AlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsResponseable interface {
    AlertRecordsMicrosoftGraphDeviceManagementGetPortalNotificationsGetPortalNotificationsGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
