package graph

import (
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55 "github.com/microsoft/kiota/abstractions/go/serialization"
)

// BookingAppointmentable 
type BookingAppointmentable interface {
    Entityable
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.Parsable
    GetAdditionalInformation()(*string)
    GetCustomerEmailAddress()(*string)
    GetCustomerId()(*string)
    GetCustomerLocation()(Locationable)
    GetCustomerName()(*string)
    GetCustomerNotes()(*string)
    GetCustomerPhone()(*string)
    GetCustomers()([]BookingCustomerInformationBaseable)
    GetCustomerTimeZone()(*string)
    GetDuration()(*i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.ISODuration)
    GetEnd()(DateTimeTimeZoneable)
    GetFilledAttendeesCount()(*int32)
    GetInvoiceAmount()(*float64)
    GetInvoiceDate()(DateTimeTimeZoneable)
    GetInvoiceId()(*string)
    GetInvoiceStatus()(*BookingInvoiceStatus)
    GetInvoiceUrl()(*string)
    GetIsLocationOnline()(*bool)
    GetJoinWebUrl()(*string)
    GetMaximumAttendeesCount()(*int32)
    GetOnlineMeetingUrl()(*string)
    GetOptOutOfCustomerEmail()(*bool)
    GetPostBuffer()(*i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.ISODuration)
    GetPreBuffer()(*i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.ISODuration)
    GetPrice()(*float64)
    GetPriceType()(*BookingPriceType)
    GetReminders()([]BookingReminderable)
    GetSelfServiceAppointmentId()(*string)
    GetServiceId()(*string)
    GetServiceLocation()(Locationable)
    GetServiceName()(*string)
    GetServiceNotes()(*string)
    GetSmsNotificationsEnabled()(*bool)
    GetStaffMemberIds()([]string)
    GetStart()(DateTimeTimeZoneable)
    SetAdditionalInformation(value *string)()
    SetCustomerEmailAddress(value *string)()
    SetCustomerId(value *string)()
    SetCustomerLocation(value Locationable)()
    SetCustomerName(value *string)()
    SetCustomerNotes(value *string)()
    SetCustomerPhone(value *string)()
    SetCustomers(value []BookingCustomerInformationBaseable)()
    SetCustomerTimeZone(value *string)()
    SetDuration(value *i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.ISODuration)()
    SetEnd(value DateTimeTimeZoneable)()
    SetFilledAttendeesCount(value *int32)()
    SetInvoiceAmount(value *float64)()
    SetInvoiceDate(value DateTimeTimeZoneable)()
    SetInvoiceId(value *string)()
    SetInvoiceStatus(value *BookingInvoiceStatus)()
    SetInvoiceUrl(value *string)()
    SetIsLocationOnline(value *bool)()
    SetJoinWebUrl(value *string)()
    SetMaximumAttendeesCount(value *int32)()
    SetOnlineMeetingUrl(value *string)()
    SetOptOutOfCustomerEmail(value *bool)()
    SetPostBuffer(value *i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.ISODuration)()
    SetPreBuffer(value *i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.ISODuration)()
    SetPrice(value *float64)()
    SetPriceType(value *BookingPriceType)()
    SetReminders(value []BookingReminderable)()
    SetSelfServiceAppointmentId(value *string)()
    SetServiceId(value *string)()
    SetServiceLocation(value Locationable)()
    SetServiceName(value *string)()
    SetServiceNotes(value *string)()
    SetSmsNotificationsEnabled(value *bool)()
    SetStaffMemberIds(value []string)()
    SetStart(value DateTimeTimeZoneable)()
}
