package graph
import (
    "strings"
    "errors"
)
// 
type CloudPcOnPremisesConnectionHealthCheckErrorType int

const (
    DNSCHECKFQDNNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE CloudPcOnPremisesConnectionHealthCheckErrorType = iota
    DNSCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKFQDNNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKINCORRECTCREDENTIALS_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKORGANIZATIONALUNITNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKORGANIZATIONALUNITINCORRECTFORMAT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKCOMPUTEROBJECTALREADYEXISTS_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKACCESSDENIED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKCREDENTIALSEXPIRED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKACCOUNTLOCKEDORDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKACCOUNTQUOTAEXCEEDED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ENDPOINTCONNECTIVITYCHECKCLOUDPCURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ENDPOINTCONNECTIVITYCHECKWVDURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ENDPOINTCONNECTIVITYCHECKINTUNEURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ENDPOINTCONNECTIVITYCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKDEVICENOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKLONGSYNCCIRCLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKCONNECTDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKDURATIONEXCEEDED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKNOSUBNETIP_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBSCRIPTIONDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKAZUREPOLICYVIOLATION_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBSCRIPTIONNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBSCRIPTIONTRANSFERRED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKGENERALSUBSCRIPTIONERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKUNSUPPORTEDVNETREGION_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKRESOURCEGROUPINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKVNETINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBNETINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKRESOURCEGROUPBEINGDELETED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKVNETBEINGMOVED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBNETDELEGATIONFAILED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBNETWITHEXTERNALRESOURCES_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORREADONLY_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORDELETE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKNOSUBSCRIPTIONREADERROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKNORESOURCEGROUPOWNERROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKNOVNETCONTRIBUTORROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKNORESOURCEGROUPNETWORKCONTRIBUTORROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    INTERNALSERVERERRORDEPLOYMENTCANCELED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    INTERNALSERVERERRORALLOCATERESOURCEFAILED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    INTERNALSERVERERRORVMDEPLOYMENTTIMEOUT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    INTERNALSERVERERRORUNABLETORUNDSCSCRIPT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    INTERNALSERVERUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    UNKNOWNFUTUREVALUE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
)

func (i CloudPcOnPremisesConnectionHealthCheckErrorType) String() string {
    return []string{"DNSCHECKFQDNNOTFOUND", "DNSCHECKUNKNOWNERROR", "ADJOINCHECKFQDNNOTFOUND", "ADJOINCHECKINCORRECTCREDENTIALS", "ADJOINCHECKORGANIZATIONALUNITNOTFOUND", "ADJOINCHECKORGANIZATIONALUNITINCORRECTFORMAT", "ADJOINCHECKCOMPUTEROBJECTALREADYEXISTS", "ADJOINCHECKACCESSDENIED", "ADJOINCHECKCREDENTIALSEXPIRED", "ADJOINCHECKACCOUNTLOCKEDORDISABLED", "ADJOINCHECKACCOUNTQUOTAEXCEEDED", "ADJOINCHECKUNKNOWNERROR", "ENDPOINTCONNECTIVITYCHECKCLOUDPCURLNOTALLOWLISTED", "ENDPOINTCONNECTIVITYCHECKWVDURLNOTALLOWLISTED", "ENDPOINTCONNECTIVITYCHECKINTUNEURLNOTALLOWLISTED", "ENDPOINTCONNECTIVITYCHECKUNKNOWNERROR", "AZUREADDEVICESYNCCHECKDEVICENOTFOUND", "AZUREADDEVICESYNCCHECKLONGSYNCCIRCLE", "AZUREADDEVICESYNCCHECKCONNECTDISABLED", "AZUREADDEVICESYNCCHECKDURATIONEXCEEDED", "AZUREADDEVICESYNCCHECKTRANSIENTSERVICEERROR", "AZUREADDEVICESYNCCHECKUNKNOWNERROR", "RESOURCEAVAILABILITYCHECKNOSUBNETIP", "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONDISABLED", "RESOURCEAVAILABILITYCHECKAZUREPOLICYVIOLATION", "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONNOTFOUND", "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONTRANSFERRED", "RESOURCEAVAILABILITYCHECKGENERALSUBSCRIPTIONERROR", "RESOURCEAVAILABILITYCHECKUNSUPPORTEDVNETREGION", "RESOURCEAVAILABILITYCHECKRESOURCEGROUPINVALID", "RESOURCEAVAILABILITYCHECKVNETINVALID", "RESOURCEAVAILABILITYCHECKSUBNETINVALID", "RESOURCEAVAILABILITYCHECKRESOURCEGROUPBEINGDELETED", "RESOURCEAVAILABILITYCHECKVNETBEINGMOVED", "RESOURCEAVAILABILITYCHECKSUBNETDELEGATIONFAILED", "RESOURCEAVAILABILITYCHECKSUBNETWITHEXTERNALRESOURCES", "RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORREADONLY", "RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORDELETE", "RESOURCEAVAILABILITYCHECKTRANSIENTSERVICEERROR", "RESOURCEAVAILABILITYCHECKUNKNOWNERROR", "PERMISSIONCHECKNOSUBSCRIPTIONREADERROLE", "PERMISSIONCHECKNORESOURCEGROUPOWNERROLE", "PERMISSIONCHECKNOVNETCONTRIBUTORROLE", "PERMISSIONCHECKNORESOURCEGROUPNETWORKCONTRIBUTORROLE", "PERMISSIONCHECKTRANSIENTSERVICEERROR", "PERMISSIONCHECKUNKNOWNERROR", "INTERNALSERVERERRORDEPLOYMENTCANCELED", "INTERNALSERVERERRORALLOCATERESOURCEFAILED", "INTERNALSERVERERRORVMDEPLOYMENTTIMEOUT", "INTERNALSERVERERRORUNABLETORUNDSCSCRIPT", "INTERNALSERVERUNKNOWNERROR", "UNKNOWNFUTUREVALUE"}[i]
}
func ParseCloudPcOnPremisesConnectionHealthCheckErrorType(v string) (interface{}, error) {
    switch strings.ToUpper(v) {
        case "DNSCHECKFQDNNOTFOUND":
            return DNSCHECKFQDNNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "DNSCHECKUNKNOWNERROR":
            return DNSCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ADJOINCHECKFQDNNOTFOUND":
            return ADJOINCHECKFQDNNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ADJOINCHECKINCORRECTCREDENTIALS":
            return ADJOINCHECKINCORRECTCREDENTIALS_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ADJOINCHECKORGANIZATIONALUNITNOTFOUND":
            return ADJOINCHECKORGANIZATIONALUNITNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ADJOINCHECKORGANIZATIONALUNITINCORRECTFORMAT":
            return ADJOINCHECKORGANIZATIONALUNITINCORRECTFORMAT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ADJOINCHECKCOMPUTEROBJECTALREADYEXISTS":
            return ADJOINCHECKCOMPUTEROBJECTALREADYEXISTS_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ADJOINCHECKACCESSDENIED":
            return ADJOINCHECKACCESSDENIED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ADJOINCHECKCREDENTIALSEXPIRED":
            return ADJOINCHECKCREDENTIALSEXPIRED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ADJOINCHECKACCOUNTLOCKEDORDISABLED":
            return ADJOINCHECKACCOUNTLOCKEDORDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ADJOINCHECKACCOUNTQUOTAEXCEEDED":
            return ADJOINCHECKACCOUNTQUOTAEXCEEDED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ADJOINCHECKUNKNOWNERROR":
            return ADJOINCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ENDPOINTCONNECTIVITYCHECKCLOUDPCURLNOTALLOWLISTED":
            return ENDPOINTCONNECTIVITYCHECKCLOUDPCURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ENDPOINTCONNECTIVITYCHECKWVDURLNOTALLOWLISTED":
            return ENDPOINTCONNECTIVITYCHECKWVDURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ENDPOINTCONNECTIVITYCHECKINTUNEURLNOTALLOWLISTED":
            return ENDPOINTCONNECTIVITYCHECKINTUNEURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "ENDPOINTCONNECTIVITYCHECKUNKNOWNERROR":
            return ENDPOINTCONNECTIVITYCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "AZUREADDEVICESYNCCHECKDEVICENOTFOUND":
            return AZUREADDEVICESYNCCHECKDEVICENOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "AZUREADDEVICESYNCCHECKLONGSYNCCIRCLE":
            return AZUREADDEVICESYNCCHECKLONGSYNCCIRCLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "AZUREADDEVICESYNCCHECKCONNECTDISABLED":
            return AZUREADDEVICESYNCCHECKCONNECTDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "AZUREADDEVICESYNCCHECKDURATIONEXCEEDED":
            return AZUREADDEVICESYNCCHECKDURATIONEXCEEDED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "AZUREADDEVICESYNCCHECKTRANSIENTSERVICEERROR":
            return AZUREADDEVICESYNCCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "AZUREADDEVICESYNCCHECKUNKNOWNERROR":
            return AZUREADDEVICESYNCCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKNOSUBNETIP":
            return RESOURCEAVAILABILITYCHECKNOSUBNETIP_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONDISABLED":
            return RESOURCEAVAILABILITYCHECKSUBSCRIPTIONDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKAZUREPOLICYVIOLATION":
            return RESOURCEAVAILABILITYCHECKAZUREPOLICYVIOLATION_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONNOTFOUND":
            return RESOURCEAVAILABILITYCHECKSUBSCRIPTIONNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONTRANSFERRED":
            return RESOURCEAVAILABILITYCHECKSUBSCRIPTIONTRANSFERRED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKGENERALSUBSCRIPTIONERROR":
            return RESOURCEAVAILABILITYCHECKGENERALSUBSCRIPTIONERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKUNSUPPORTEDVNETREGION":
            return RESOURCEAVAILABILITYCHECKUNSUPPORTEDVNETREGION_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKRESOURCEGROUPINVALID":
            return RESOURCEAVAILABILITYCHECKRESOURCEGROUPINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKVNETINVALID":
            return RESOURCEAVAILABILITYCHECKVNETINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKSUBNETINVALID":
            return RESOURCEAVAILABILITYCHECKSUBNETINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKRESOURCEGROUPBEINGDELETED":
            return RESOURCEAVAILABILITYCHECKRESOURCEGROUPBEINGDELETED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKVNETBEINGMOVED":
            return RESOURCEAVAILABILITYCHECKVNETBEINGMOVED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKSUBNETDELEGATIONFAILED":
            return RESOURCEAVAILABILITYCHECKSUBNETDELEGATIONFAILED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKSUBNETWITHEXTERNALRESOURCES":
            return RESOURCEAVAILABILITYCHECKSUBNETWITHEXTERNALRESOURCES_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORREADONLY":
            return RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORREADONLY_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORDELETE":
            return RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORDELETE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKTRANSIENTSERVICEERROR":
            return RESOURCEAVAILABILITYCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "RESOURCEAVAILABILITYCHECKUNKNOWNERROR":
            return RESOURCEAVAILABILITYCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "PERMISSIONCHECKNOSUBSCRIPTIONREADERROLE":
            return PERMISSIONCHECKNOSUBSCRIPTIONREADERROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "PERMISSIONCHECKNORESOURCEGROUPOWNERROLE":
            return PERMISSIONCHECKNORESOURCEGROUPOWNERROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "PERMISSIONCHECKNOVNETCONTRIBUTORROLE":
            return PERMISSIONCHECKNOVNETCONTRIBUTORROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "PERMISSIONCHECKNORESOURCEGROUPNETWORKCONTRIBUTORROLE":
            return PERMISSIONCHECKNORESOURCEGROUPNETWORKCONTRIBUTORROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "PERMISSIONCHECKTRANSIENTSERVICEERROR":
            return PERMISSIONCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "PERMISSIONCHECKUNKNOWNERROR":
            return PERMISSIONCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "INTERNALSERVERERRORDEPLOYMENTCANCELED":
            return INTERNALSERVERERRORDEPLOYMENTCANCELED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "INTERNALSERVERERRORALLOCATERESOURCEFAILED":
            return INTERNALSERVERERRORALLOCATERESOURCEFAILED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "INTERNALSERVERERRORVMDEPLOYMENTTIMEOUT":
            return INTERNALSERVERERRORVMDEPLOYMENTTIMEOUT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "INTERNALSERVERERRORUNABLETORUNDSCSCRIPT":
            return INTERNALSERVERERRORUNABLETORUNDSCSCRIPT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "INTERNALSERVERUNKNOWNERROR":
            return INTERNALSERVERUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
        case "UNKNOWNFUTUREVALUE":
            return UNKNOWNFUTUREVALUE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE, nil
    }
    return 0, errors.New("Unknown CloudPcOnPremisesConnectionHealthCheckErrorType value: " + v)
}
func SerializeCloudPcOnPremisesConnectionHealthCheckErrorType(values []CloudPcOnPremisesConnectionHealthCheckErrorType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
