package graph
import (
    "strings"
    "errors"
)
// 
type CloudPcOnPremisesConnectionHealthCheckErrorType int

const (
    DNSCHECKFQDNNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE CloudPcOnPremisesConnectionHealthCheckErrorType = iota
    DNSCHECKNAMEWITHINVALIDCHARACTER_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    DNSCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKFQDNNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKINCORRECTCREDENTIALS_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKORGANIZATIONALUNITNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKORGANIZATIONALUNITINCORRECTFORMAT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKCOMPUTEROBJECTALREADYEXISTS_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKACCESSDENIED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKCREDENTIALSEXPIRED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKACCOUNTLOCKEDORDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKACCOUNTQUOTAEXCEEDED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ADJOINCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ENDPOINTCONNECTIVITYCHECKCLOUDPCURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ENDPOINTCONNECTIVITYCHECKWVDURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ENDPOINTCONNECTIVITYCHECKINTUNEURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    ENDPOINTCONNECTIVITYCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKDEVICENOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKLONGSYNCCIRCLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKCONNECTDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKDURATIONEXCEEDED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKSCPNOTCONFIGURED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    AZUREADDEVICESYNCCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKNOSUBNETIP_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBSCRIPTIONDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKAZUREPOLICYVIOLATION_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBSCRIPTIONNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBSCRIPTIONTRANSFERRED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKGENERALSUBSCRIPTIONERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKUNSUPPORTEDVNETREGION_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKRESOURCEGROUPINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKVNETINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBNETINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKRESOURCEGROUPBEINGDELETED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKVNETBEINGMOVED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBNETDELEGATIONFAILED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKSUBNETWITHEXTERNALRESOURCES_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORREADONLY_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORDELETE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    RESOURCEAVAILABILITYCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKNOSUBSCRIPTIONREADERROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKNORESOURCEGROUPOWNERROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKNOVNETCONTRIBUTORROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKNORESOURCEGROUPNETWORKCONTRIBUTORROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    PERMISSIONCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    INTERNALSERVERERRORDEPLOYMENTCANCELED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    INTERNALSERVERERRORALLOCATERESOURCEFAILED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    INTERNALSERVERERRORVMDEPLOYMENTTIMEOUT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    INTERNALSERVERERRORUNABLETORUNDSCSCRIPT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    INTERNALSERVERUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    UNKNOWNFUTUREVALUE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
)

func (i CloudPcOnPremisesConnectionHealthCheckErrorType) String() string {
    return []string{"DNSCHECKFQDNNOTFOUND", "DNSCHECKNAMEWITHINVALIDCHARACTER", "DNSCHECKUNKNOWNERROR", "ADJOINCHECKFQDNNOTFOUND", "ADJOINCHECKINCORRECTCREDENTIALS", "ADJOINCHECKORGANIZATIONALUNITNOTFOUND", "ADJOINCHECKORGANIZATIONALUNITINCORRECTFORMAT", "ADJOINCHECKCOMPUTEROBJECTALREADYEXISTS", "ADJOINCHECKACCESSDENIED", "ADJOINCHECKCREDENTIALSEXPIRED", "ADJOINCHECKACCOUNTLOCKEDORDISABLED", "ADJOINCHECKACCOUNTQUOTAEXCEEDED", "ADJOINCHECKUNKNOWNERROR", "ENDPOINTCONNECTIVITYCHECKCLOUDPCURLNOTALLOWLISTED", "ENDPOINTCONNECTIVITYCHECKWVDURLNOTALLOWLISTED", "ENDPOINTCONNECTIVITYCHECKINTUNEURLNOTALLOWLISTED", "ENDPOINTCONNECTIVITYCHECKUNKNOWNERROR", "AZUREADDEVICESYNCCHECKDEVICENOTFOUND", "AZUREADDEVICESYNCCHECKLONGSYNCCIRCLE", "AZUREADDEVICESYNCCHECKCONNECTDISABLED", "AZUREADDEVICESYNCCHECKDURATIONEXCEEDED", "AZUREADDEVICESYNCCHECKSCPNOTCONFIGURED", "AZUREADDEVICESYNCCHECKTRANSIENTSERVICEERROR", "AZUREADDEVICESYNCCHECKUNKNOWNERROR", "RESOURCEAVAILABILITYCHECKNOSUBNETIP", "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONDISABLED", "RESOURCEAVAILABILITYCHECKAZUREPOLICYVIOLATION", "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONNOTFOUND", "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONTRANSFERRED", "RESOURCEAVAILABILITYCHECKGENERALSUBSCRIPTIONERROR", "RESOURCEAVAILABILITYCHECKUNSUPPORTEDVNETREGION", "RESOURCEAVAILABILITYCHECKRESOURCEGROUPINVALID", "RESOURCEAVAILABILITYCHECKVNETINVALID", "RESOURCEAVAILABILITYCHECKSUBNETINVALID", "RESOURCEAVAILABILITYCHECKRESOURCEGROUPBEINGDELETED", "RESOURCEAVAILABILITYCHECKVNETBEINGMOVED", "RESOURCEAVAILABILITYCHECKSUBNETDELEGATIONFAILED", "RESOURCEAVAILABILITYCHECKSUBNETWITHEXTERNALRESOURCES", "RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORREADONLY", "RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORDELETE", "RESOURCEAVAILABILITYCHECKTRANSIENTSERVICEERROR", "RESOURCEAVAILABILITYCHECKUNKNOWNERROR", "PERMISSIONCHECKNOSUBSCRIPTIONREADERROLE", "PERMISSIONCHECKNORESOURCEGROUPOWNERROLE", "PERMISSIONCHECKNOVNETCONTRIBUTORROLE", "PERMISSIONCHECKNORESOURCEGROUPNETWORKCONTRIBUTORROLE", "PERMISSIONCHECKTRANSIENTSERVICEERROR", "PERMISSIONCHECKUNKNOWNERROR", "INTERNALSERVERERRORDEPLOYMENTCANCELED", "INTERNALSERVERERRORALLOCATERESOURCEFAILED", "INTERNALSERVERERRORVMDEPLOYMENTTIMEOUT", "INTERNALSERVERERRORUNABLETORUNDSCSCRIPT", "INTERNALSERVERUNKNOWNERROR", "UNKNOWNFUTUREVALUE"}[i]
}
func ParseCloudPcOnPremisesConnectionHealthCheckErrorType(v string) (interface{}, error) {
    result := DNSCHECKFQDNNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
    switch strings.ToUpper(v) {
        case "DNSCHECKFQDNNOTFOUND":
            result = DNSCHECKFQDNNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "DNSCHECKNAMEWITHINVALIDCHARACTER":
            result = DNSCHECKNAMEWITHINVALIDCHARACTER_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "DNSCHECKUNKNOWNERROR":
            result = DNSCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ADJOINCHECKFQDNNOTFOUND":
            result = ADJOINCHECKFQDNNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ADJOINCHECKINCORRECTCREDENTIALS":
            result = ADJOINCHECKINCORRECTCREDENTIALS_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ADJOINCHECKORGANIZATIONALUNITNOTFOUND":
            result = ADJOINCHECKORGANIZATIONALUNITNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ADJOINCHECKORGANIZATIONALUNITINCORRECTFORMAT":
            result = ADJOINCHECKORGANIZATIONALUNITINCORRECTFORMAT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ADJOINCHECKCOMPUTEROBJECTALREADYEXISTS":
            result = ADJOINCHECKCOMPUTEROBJECTALREADYEXISTS_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ADJOINCHECKACCESSDENIED":
            result = ADJOINCHECKACCESSDENIED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ADJOINCHECKCREDENTIALSEXPIRED":
            result = ADJOINCHECKCREDENTIALSEXPIRED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ADJOINCHECKACCOUNTLOCKEDORDISABLED":
            result = ADJOINCHECKACCOUNTLOCKEDORDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ADJOINCHECKACCOUNTQUOTAEXCEEDED":
            result = ADJOINCHECKACCOUNTQUOTAEXCEEDED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ADJOINCHECKUNKNOWNERROR":
            result = ADJOINCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ENDPOINTCONNECTIVITYCHECKCLOUDPCURLNOTALLOWLISTED":
            result = ENDPOINTCONNECTIVITYCHECKCLOUDPCURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ENDPOINTCONNECTIVITYCHECKWVDURLNOTALLOWLISTED":
            result = ENDPOINTCONNECTIVITYCHECKWVDURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ENDPOINTCONNECTIVITYCHECKINTUNEURLNOTALLOWLISTED":
            result = ENDPOINTCONNECTIVITYCHECKINTUNEURLNOTALLOWLISTED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "ENDPOINTCONNECTIVITYCHECKUNKNOWNERROR":
            result = ENDPOINTCONNECTIVITYCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "AZUREADDEVICESYNCCHECKDEVICENOTFOUND":
            result = AZUREADDEVICESYNCCHECKDEVICENOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "AZUREADDEVICESYNCCHECKLONGSYNCCIRCLE":
            result = AZUREADDEVICESYNCCHECKLONGSYNCCIRCLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "AZUREADDEVICESYNCCHECKCONNECTDISABLED":
            result = AZUREADDEVICESYNCCHECKCONNECTDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "AZUREADDEVICESYNCCHECKDURATIONEXCEEDED":
            result = AZUREADDEVICESYNCCHECKDURATIONEXCEEDED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "AZUREADDEVICESYNCCHECKSCPNOTCONFIGURED":
            result = AZUREADDEVICESYNCCHECKSCPNOTCONFIGURED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "AZUREADDEVICESYNCCHECKTRANSIENTSERVICEERROR":
            result = AZUREADDEVICESYNCCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "AZUREADDEVICESYNCCHECKUNKNOWNERROR":
            result = AZUREADDEVICESYNCCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKNOSUBNETIP":
            result = RESOURCEAVAILABILITYCHECKNOSUBNETIP_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONDISABLED":
            result = RESOURCEAVAILABILITYCHECKSUBSCRIPTIONDISABLED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKAZUREPOLICYVIOLATION":
            result = RESOURCEAVAILABILITYCHECKAZUREPOLICYVIOLATION_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONNOTFOUND":
            result = RESOURCEAVAILABILITYCHECKSUBSCRIPTIONNOTFOUND_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKSUBSCRIPTIONTRANSFERRED":
            result = RESOURCEAVAILABILITYCHECKSUBSCRIPTIONTRANSFERRED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKGENERALSUBSCRIPTIONERROR":
            result = RESOURCEAVAILABILITYCHECKGENERALSUBSCRIPTIONERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKUNSUPPORTEDVNETREGION":
            result = RESOURCEAVAILABILITYCHECKUNSUPPORTEDVNETREGION_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKRESOURCEGROUPINVALID":
            result = RESOURCEAVAILABILITYCHECKRESOURCEGROUPINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKVNETINVALID":
            result = RESOURCEAVAILABILITYCHECKVNETINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKSUBNETINVALID":
            result = RESOURCEAVAILABILITYCHECKSUBNETINVALID_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKRESOURCEGROUPBEINGDELETED":
            result = RESOURCEAVAILABILITYCHECKRESOURCEGROUPBEINGDELETED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKVNETBEINGMOVED":
            result = RESOURCEAVAILABILITYCHECKVNETBEINGMOVED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKSUBNETDELEGATIONFAILED":
            result = RESOURCEAVAILABILITYCHECKSUBNETDELEGATIONFAILED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKSUBNETWITHEXTERNALRESOURCES":
            result = RESOURCEAVAILABILITYCHECKSUBNETWITHEXTERNALRESOURCES_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORREADONLY":
            result = RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORREADONLY_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORDELETE":
            result = RESOURCEAVAILABILITYCHECKRESOURCEGROUPLOCKEDFORDELETE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKTRANSIENTSERVICEERROR":
            result = RESOURCEAVAILABILITYCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "RESOURCEAVAILABILITYCHECKUNKNOWNERROR":
            result = RESOURCEAVAILABILITYCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "PERMISSIONCHECKNOSUBSCRIPTIONREADERROLE":
            result = PERMISSIONCHECKNOSUBSCRIPTIONREADERROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "PERMISSIONCHECKNORESOURCEGROUPOWNERROLE":
            result = PERMISSIONCHECKNORESOURCEGROUPOWNERROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "PERMISSIONCHECKNOVNETCONTRIBUTORROLE":
            result = PERMISSIONCHECKNOVNETCONTRIBUTORROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "PERMISSIONCHECKNORESOURCEGROUPNETWORKCONTRIBUTORROLE":
            result = PERMISSIONCHECKNORESOURCEGROUPNETWORKCONTRIBUTORROLE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "PERMISSIONCHECKTRANSIENTSERVICEERROR":
            result = PERMISSIONCHECKTRANSIENTSERVICEERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "PERMISSIONCHECKUNKNOWNERROR":
            result = PERMISSIONCHECKUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "INTERNALSERVERERRORDEPLOYMENTCANCELED":
            result = INTERNALSERVERERRORDEPLOYMENTCANCELED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "INTERNALSERVERERRORALLOCATERESOURCEFAILED":
            result = INTERNALSERVERERRORALLOCATERESOURCEFAILED_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "INTERNALSERVERERRORVMDEPLOYMENTTIMEOUT":
            result = INTERNALSERVERERRORVMDEPLOYMENTTIMEOUT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "INTERNALSERVERERRORUNABLETORUNDSCSCRIPT":
            result = INTERNALSERVERERRORUNABLETORUNDSCSCRIPT_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "INTERNALSERVERUNKNOWNERROR":
            result = INTERNALSERVERUNKNOWNERROR_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        case "UNKNOWNFUTUREVALUE":
            result = UNKNOWNFUTUREVALUE_CLOUDPCONPREMISESCONNECTIONHEALTHCHECKERRORTYPE
        default:
            return 0, errors.New("Unknown CloudPcOnPremisesConnectionHealthCheckErrorType value: " + v)
    }
    return &result, nil
}
func SerializeCloudPcOnPremisesConnectionHealthCheckErrorType(values []CloudPcOnPremisesConnectionHealthCheckErrorType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
