package graph
import (
    "strings"
    "errors"
)
// 
type DeviceManagementTemplateSubtype int

const (
    NONE_DEVICEMANAGEMENTTEMPLATESUBTYPE DeviceManagementTemplateSubtype = iota
    FIREWALL_DEVICEMANAGEMENTTEMPLATESUBTYPE
    DISKENCRYPTION_DEVICEMANAGEMENTTEMPLATESUBTYPE
    ATTACKSURFACEREDUCTION_DEVICEMANAGEMENTTEMPLATESUBTYPE
    ENDPOINTDETECTIONREPONSE_DEVICEMANAGEMENTTEMPLATESUBTYPE
    ACCOUNTPROTECTION_DEVICEMANAGEMENTTEMPLATESUBTYPE
    ANTIVIRUS_DEVICEMANAGEMENTTEMPLATESUBTYPE
    FIREWALLSHAREDAPPLIST_DEVICEMANAGEMENTTEMPLATESUBTYPE
    FIREWALLSHAREDIPLIST_DEVICEMANAGEMENTTEMPLATESUBTYPE
    FIREWALLSHAREDPORTLIST_DEVICEMANAGEMENTTEMPLATESUBTYPE
)

func (i DeviceManagementTemplateSubtype) String() string {
    return []string{"NONE", "FIREWALL", "DISKENCRYPTION", "ATTACKSURFACEREDUCTION", "ENDPOINTDETECTIONREPONSE", "ACCOUNTPROTECTION", "ANTIVIRUS", "FIREWALLSHAREDAPPLIST", "FIREWALLSHAREDIPLIST", "FIREWALLSHAREDPORTLIST"}[i]
}
func ParseDeviceManagementTemplateSubtype(v string) (interface{}, error) {
    result := NONE_DEVICEMANAGEMENTTEMPLATESUBTYPE
    switch strings.ToUpper(v) {
        case "NONE":
            result = NONE_DEVICEMANAGEMENTTEMPLATESUBTYPE
        case "FIREWALL":
            result = FIREWALL_DEVICEMANAGEMENTTEMPLATESUBTYPE
        case "DISKENCRYPTION":
            result = DISKENCRYPTION_DEVICEMANAGEMENTTEMPLATESUBTYPE
        case "ATTACKSURFACEREDUCTION":
            result = ATTACKSURFACEREDUCTION_DEVICEMANAGEMENTTEMPLATESUBTYPE
        case "ENDPOINTDETECTIONREPONSE":
            result = ENDPOINTDETECTIONREPONSE_DEVICEMANAGEMENTTEMPLATESUBTYPE
        case "ACCOUNTPROTECTION":
            result = ACCOUNTPROTECTION_DEVICEMANAGEMENTTEMPLATESUBTYPE
        case "ANTIVIRUS":
            result = ANTIVIRUS_DEVICEMANAGEMENTTEMPLATESUBTYPE
        case "FIREWALLSHAREDAPPLIST":
            result = FIREWALLSHAREDAPPLIST_DEVICEMANAGEMENTTEMPLATESUBTYPE
        case "FIREWALLSHAREDIPLIST":
            result = FIREWALLSHAREDIPLIST_DEVICEMANAGEMENTTEMPLATESUBTYPE
        case "FIREWALLSHAREDPORTLIST":
            result = FIREWALLSHAREDPORTLIST_DEVICEMANAGEMENTTEMPLATESUBTYPE
        default:
            return 0, errors.New("Unknown DeviceManagementTemplateSubtype value: " + v)
    }
    return &result, nil
}
func SerializeDeviceManagementTemplateSubtype(values []DeviceManagementTemplateSubtype) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
