package graph
import (
    "strings"
    "errors"
)
// 
type DeviceManagementConfigurationTemplateFamily int

const (
    NONE_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY DeviceManagementConfigurationTemplateFamily = iota
    ENDPOINTSECURITYANTIVIRUS_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
    ENDPOINTSECURITYDISKENCRYPTION_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
    ENDPOINTSECURITYFIREWALL_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
    ENDPOINTSECURITYENDPOINTDETECTIONANDRESPONSE_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
    ENDPOINTSECURITYATTACKSURFACEREDUCTION_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
    ENDPOINTSECURITYACCOUNTPROTECTION_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
    ENDPOINTSECURITYAPPLICATIONCONTROL_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
    BASELINE_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
)

func (i DeviceManagementConfigurationTemplateFamily) String() string {
    return []string{"NONE", "ENDPOINTSECURITYANTIVIRUS", "ENDPOINTSECURITYDISKENCRYPTION", "ENDPOINTSECURITYFIREWALL", "ENDPOINTSECURITYENDPOINTDETECTIONANDRESPONSE", "ENDPOINTSECURITYATTACKSURFACEREDUCTION", "ENDPOINTSECURITYACCOUNTPROTECTION", "ENDPOINTSECURITYAPPLICATIONCONTROL", "BASELINE"}[i]
}
func ParseDeviceManagementConfigurationTemplateFamily(v string) (interface{}, error) {
    result := NONE_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
    switch strings.ToUpper(v) {
        case "NONE":
            result = NONE_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
        case "ENDPOINTSECURITYANTIVIRUS":
            result = ENDPOINTSECURITYANTIVIRUS_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
        case "ENDPOINTSECURITYDISKENCRYPTION":
            result = ENDPOINTSECURITYDISKENCRYPTION_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
        case "ENDPOINTSECURITYFIREWALL":
            result = ENDPOINTSECURITYFIREWALL_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
        case "ENDPOINTSECURITYENDPOINTDETECTIONANDRESPONSE":
            result = ENDPOINTSECURITYENDPOINTDETECTIONANDRESPONSE_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
        case "ENDPOINTSECURITYATTACKSURFACEREDUCTION":
            result = ENDPOINTSECURITYATTACKSURFACEREDUCTION_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
        case "ENDPOINTSECURITYACCOUNTPROTECTION":
            result = ENDPOINTSECURITYACCOUNTPROTECTION_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
        case "ENDPOINTSECURITYAPPLICATIONCONTROL":
            result = ENDPOINTSECURITYAPPLICATIONCONTROL_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
        case "BASELINE":
            result = BASELINE_DEVICEMANAGEMENTCONFIGURATIONTEMPLATEFAMILY
        default:
            return 0, errors.New("Unknown DeviceManagementConfigurationTemplateFamily value: " + v)
    }
    return &result, nil
}
func SerializeDeviceManagementConfigurationTemplateFamily(values []DeviceManagementConfigurationTemplateFamily) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
