package graph

import (
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55 "github.com/microsoft/kiota/abstractions/go/serialization"
)

// HardwareInformationable 
type HardwareInformationable interface {
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.AdditionalDataHolder
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.Parsable
    GetBatteryChargeCycles()(*int32)
    GetBatteryHealthPercentage()(*int32)
    GetBatterySerialNumber()(*string)
    GetCellularTechnology()(*string)
    GetDeviceFullQualifiedDomainName()(*string)
    GetDeviceGuardLocalSystemAuthorityCredentialGuardState()(*DeviceGuardLocalSystemAuthorityCredentialGuardState)
    GetDeviceGuardVirtualizationBasedSecurityHardwareRequirementState()(*DeviceGuardVirtualizationBasedSecurityHardwareRequirementState)
    GetDeviceGuardVirtualizationBasedSecurityState()(*DeviceGuardVirtualizationBasedSecurityState)
    GetEsimIdentifier()(*string)
    GetFreeStorageSpace()(*int32)
    GetImei()(*string)
    GetIpAddressV4()(*string)
    GetIsEncrypted()(*bool)
    GetIsSharedDevice()(*bool)
    GetIsSupervised()(*bool)
    GetManufacturer()(*string)
    GetMeid()(*string)
    GetModel()(*string)
    GetOperatingSystemEdition()(*string)
    GetOperatingSystemLanguage()(*string)
    GetOperatingSystemProductType()(*int32)
    GetOsBuildNumber()(*string)
    GetPhoneNumber()(*string)
    GetSerialNumber()(*string)
    GetSharedDeviceCachedUsers()([]SharedAppleDeviceUserable)
    GetSubnetAddress()(*string)
    GetSubscriberCarrier()(*string)
    GetSystemManagementBIOSVersion()(*string)
    GetTotalStorageSpace()(*int32)
    GetTpmManufacturer()(*string)
    GetTpmSpecificationVersion()(*string)
    GetTpmVersion()(*string)
    GetWifiMac()(*string)
    SetBatteryChargeCycles(value *int32)()
    SetBatteryHealthPercentage(value *int32)()
    SetBatterySerialNumber(value *string)()
    SetCellularTechnology(value *string)()
    SetDeviceFullQualifiedDomainName(value *string)()
    SetDeviceGuardLocalSystemAuthorityCredentialGuardState(value *DeviceGuardLocalSystemAuthorityCredentialGuardState)()
    SetDeviceGuardVirtualizationBasedSecurityHardwareRequirementState(value *DeviceGuardVirtualizationBasedSecurityHardwareRequirementState)()
    SetDeviceGuardVirtualizationBasedSecurityState(value *DeviceGuardVirtualizationBasedSecurityState)()
    SetEsimIdentifier(value *string)()
    SetFreeStorageSpace(value *int32)()
    SetImei(value *string)()
    SetIpAddressV4(value *string)()
    SetIsEncrypted(value *bool)()
    SetIsSharedDevice(value *bool)()
    SetIsSupervised(value *bool)()
    SetManufacturer(value *string)()
    SetMeid(value *string)()
    SetModel(value *string)()
    SetOperatingSystemEdition(value *string)()
    SetOperatingSystemLanguage(value *string)()
    SetOperatingSystemProductType(value *int32)()
    SetOsBuildNumber(value *string)()
    SetPhoneNumber(value *string)()
    SetSerialNumber(value *string)()
    SetSharedDeviceCachedUsers(value []SharedAppleDeviceUserable)()
    SetSubnetAddress(value *string)()
    SetSubscriberCarrier(value *string)()
    SetSystemManagementBIOSVersion(value *string)()
    SetTotalStorageSpace(value *int32)()
    SetTpmManufacturer(value *string)()
    SetTpmSpecificationVersion(value *string)()
    SetTpmVersion(value *string)()
    SetWifiMac(value *string)()
}
