package graph
import (
    "strings"
    "errors"
)
// 
type MacOSSoftwareUpdateState int

const (
    SUCCESS_MACOSSOFTWAREUPDATESTATE MacOSSoftwareUpdateState = iota
    DOWNLOADING_MACOSSOFTWAREUPDATESTATE
    DOWNLOADED_MACOSSOFTWAREUPDATESTATE
    INSTALLING_MACOSSOFTWAREUPDATESTATE
    IDLE_MACOSSOFTWAREUPDATESTATE
    AVAILABLE_MACOSSOFTWAREUPDATESTATE
    SCHEDULED_MACOSSOFTWAREUPDATESTATE
    DOWNLOADFAILED_MACOSSOFTWAREUPDATESTATE
    DOWNLOADINSUFFICIENTSPACE_MACOSSOFTWAREUPDATESTATE
    DOWNLOADINSUFFICIENTPOWER_MACOSSOFTWAREUPDATESTATE
    DOWNLOADINSUFFICIENTNETWORK_MACOSSOFTWAREUPDATESTATE
    INSTALLINSUFFICIENTSPACE_MACOSSOFTWAREUPDATESTATE
    INSTALLINSUFFICIENTPOWER_MACOSSOFTWAREUPDATESTATE
    INSTALLFAILED_MACOSSOFTWAREUPDATESTATE
    COMMANDFAILED_MACOSSOFTWAREUPDATESTATE
)

func (i MacOSSoftwareUpdateState) String() string {
    return []string{"SUCCESS", "DOWNLOADING", "DOWNLOADED", "INSTALLING", "IDLE", "AVAILABLE", "SCHEDULED", "DOWNLOADFAILED", "DOWNLOADINSUFFICIENTSPACE", "DOWNLOADINSUFFICIENTPOWER", "DOWNLOADINSUFFICIENTNETWORK", "INSTALLINSUFFICIENTSPACE", "INSTALLINSUFFICIENTPOWER", "INSTALLFAILED", "COMMANDFAILED"}[i]
}
func ParseMacOSSoftwareUpdateState(v string) (interface{}, error) {
    result := SUCCESS_MACOSSOFTWAREUPDATESTATE
    switch strings.ToUpper(v) {
        case "SUCCESS":
            result = SUCCESS_MACOSSOFTWAREUPDATESTATE
        case "DOWNLOADING":
            result = DOWNLOADING_MACOSSOFTWAREUPDATESTATE
        case "DOWNLOADED":
            result = DOWNLOADED_MACOSSOFTWAREUPDATESTATE
        case "INSTALLING":
            result = INSTALLING_MACOSSOFTWAREUPDATESTATE
        case "IDLE":
            result = IDLE_MACOSSOFTWAREUPDATESTATE
        case "AVAILABLE":
            result = AVAILABLE_MACOSSOFTWAREUPDATESTATE
        case "SCHEDULED":
            result = SCHEDULED_MACOSSOFTWAREUPDATESTATE
        case "DOWNLOADFAILED":
            result = DOWNLOADFAILED_MACOSSOFTWAREUPDATESTATE
        case "DOWNLOADINSUFFICIENTSPACE":
            result = DOWNLOADINSUFFICIENTSPACE_MACOSSOFTWAREUPDATESTATE
        case "DOWNLOADINSUFFICIENTPOWER":
            result = DOWNLOADINSUFFICIENTPOWER_MACOSSOFTWAREUPDATESTATE
        case "DOWNLOADINSUFFICIENTNETWORK":
            result = DOWNLOADINSUFFICIENTNETWORK_MACOSSOFTWAREUPDATESTATE
        case "INSTALLINSUFFICIENTSPACE":
            result = INSTALLINSUFFICIENTSPACE_MACOSSOFTWAREUPDATESTATE
        case "INSTALLINSUFFICIENTPOWER":
            result = INSTALLINSUFFICIENTPOWER_MACOSSOFTWAREUPDATESTATE
        case "INSTALLFAILED":
            result = INSTALLFAILED_MACOSSOFTWAREUPDATESTATE
        case "COMMANDFAILED":
            result = COMMANDFAILED_MACOSSOFTWAREUPDATESTATE
        default:
            return 0, errors.New("Unknown MacOSSoftwareUpdateState value: " + v)
    }
    return &result, nil
}
func SerializeMacOSSoftwareUpdateState(values []MacOSSoftwareUpdateState) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
