package graph
import (
    "strings"
    "errors"
)
// 
type PrintPresentationDirection int

const (
    CLOCKWISEFROMTOPLEFT_PRINTPRESENTATIONDIRECTION PrintPresentationDirection = iota
    COUNTERCLOCKWISEFROMTOPLEFT_PRINTPRESENTATIONDIRECTION
    COUNTERCLOCKWISEFROMTOPRIGHT_PRINTPRESENTATIONDIRECTION
    CLOCKWISEFROMTOPRIGHT_PRINTPRESENTATIONDIRECTION
    COUNTERCLOCKWISEFROMBOTTOMLEFT_PRINTPRESENTATIONDIRECTION
    CLOCKWISEFROMBOTTOMLEFT_PRINTPRESENTATIONDIRECTION
    COUNTERCLOCKWISEFROMBOTTOMRIGHT_PRINTPRESENTATIONDIRECTION
    CLOCKWISEFROMBOTTOMRIGHT_PRINTPRESENTATIONDIRECTION
)

func (i PrintPresentationDirection) String() string {
    return []string{"CLOCKWISEFROMTOPLEFT", "COUNTERCLOCKWISEFROMTOPLEFT", "COUNTERCLOCKWISEFROMTOPRIGHT", "CLOCKWISEFROMTOPRIGHT", "COUNTERCLOCKWISEFROMBOTTOMLEFT", "CLOCKWISEFROMBOTTOMLEFT", "COUNTERCLOCKWISEFROMBOTTOMRIGHT", "CLOCKWISEFROMBOTTOMRIGHT"}[i]
}
func ParsePrintPresentationDirection(v string) (interface{}, error) {
    switch strings.ToUpper(v) {
        case "CLOCKWISEFROMTOPLEFT":
            return CLOCKWISEFROMTOPLEFT_PRINTPRESENTATIONDIRECTION, nil
        case "COUNTERCLOCKWISEFROMTOPLEFT":
            return COUNTERCLOCKWISEFROMTOPLEFT_PRINTPRESENTATIONDIRECTION, nil
        case "COUNTERCLOCKWISEFROMTOPRIGHT":
            return COUNTERCLOCKWISEFROMTOPRIGHT_PRINTPRESENTATIONDIRECTION, nil
        case "CLOCKWISEFROMTOPRIGHT":
            return CLOCKWISEFROMTOPRIGHT_PRINTPRESENTATIONDIRECTION, nil
        case "COUNTERCLOCKWISEFROMBOTTOMLEFT":
            return COUNTERCLOCKWISEFROMBOTTOMLEFT_PRINTPRESENTATIONDIRECTION, nil
        case "CLOCKWISEFROMBOTTOMLEFT":
            return CLOCKWISEFROMBOTTOMLEFT_PRINTPRESENTATIONDIRECTION, nil
        case "COUNTERCLOCKWISEFROMBOTTOMRIGHT":
            return COUNTERCLOCKWISEFROMBOTTOMRIGHT_PRINTPRESENTATIONDIRECTION, nil
        case "CLOCKWISEFROMBOTTOMRIGHT":
            return CLOCKWISEFROMBOTTOMRIGHT_PRINTPRESENTATIONDIRECTION, nil
    }
    return 0, errors.New("Unknown PrintPresentationDirection value: " + v)
}
func SerializePrintPresentationDirection(values []PrintPresentationDirection) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
