package graph

import (
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55 "github.com/microsoft/kiota/abstractions/go/serialization"
)

// PrinterCapabilitiesable 
type PrinterCapabilitiesable interface {
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.AdditionalDataHolder
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.Parsable
    GetBottomMargins()([]int32)
    GetCollation()(*bool)
    GetColorModes()([]PrintColorMode)
    GetContentTypes()([]string)
    GetCopiesPerJob()(IntegerRangeable)
    GetDpis()([]int32)
    GetDuplexModes()([]PrintDuplexMode)
    GetFeedDirections()([]PrinterFeedDirection)
    GetFeedOrientations()([]PrinterFeedOrientation)
    GetFinishings()([]PrintFinishing)
    GetInputBins()([]string)
    GetIsColorPrintingSupported()(*bool)
    GetIsPageRangeSupported()(*bool)
    GetLeftMargins()([]int32)
    GetMediaColors()([]string)
    GetMediaSizes()([]string)
    GetMediaTypes()([]string)
    GetMultipageLayouts()([]PrintMultipageLayout)
    GetOrientations()([]PrintOrientation)
    GetOutputBins()([]string)
    GetPagesPerSheet()([]int32)
    GetQualities()([]PrintQuality)
    GetRightMargins()([]int32)
    GetScalings()([]PrintScaling)
    GetSupportedColorConfigurations()([]PrintColorConfiguration)
    GetSupportedCopiesPerJob()(IntegerRangeable)
    GetSupportedDocumentMimeTypes()([]string)
    GetSupportedDuplexConfigurations()([]PrintDuplexConfiguration)
    GetSupportedFinishings()([]PrintFinishing)
    GetSupportedMediaColors()([]string)
    GetSupportedMediaSizes()([]string)
    GetSupportedMediaTypes()([]PrintMediaType)
    GetSupportedOrientations()([]PrintOrientation)
    GetSupportedOutputBins()([]string)
    GetSupportedPagesPerSheet()(IntegerRangeable)
    GetSupportedPresentationDirections()([]PrintPresentationDirection)
    GetSupportedPrintQualities()([]PrintQuality)
    GetSupportsFitPdfToPage()(*bool)
    GetTopMargins()([]int32)
    SetBottomMargins(value []int32)()
    SetCollation(value *bool)()
    SetColorModes(value []PrintColorMode)()
    SetContentTypes(value []string)()
    SetCopiesPerJob(value IntegerRangeable)()
    SetDpis(value []int32)()
    SetDuplexModes(value []PrintDuplexMode)()
    SetFeedDirections(value []PrinterFeedDirection)()
    SetFeedOrientations(value []PrinterFeedOrientation)()
    SetFinishings(value []PrintFinishing)()
    SetInputBins(value []string)()
    SetIsColorPrintingSupported(value *bool)()
    SetIsPageRangeSupported(value *bool)()
    SetLeftMargins(value []int32)()
    SetMediaColors(value []string)()
    SetMediaSizes(value []string)()
    SetMediaTypes(value []string)()
    SetMultipageLayouts(value []PrintMultipageLayout)()
    SetOrientations(value []PrintOrientation)()
    SetOutputBins(value []string)()
    SetPagesPerSheet(value []int32)()
    SetQualities(value []PrintQuality)()
    SetRightMargins(value []int32)()
    SetScalings(value []PrintScaling)()
    SetSupportedColorConfigurations(value []PrintColorConfiguration)()
    SetSupportedCopiesPerJob(value IntegerRangeable)()
    SetSupportedDocumentMimeTypes(value []string)()
    SetSupportedDuplexConfigurations(value []PrintDuplexConfiguration)()
    SetSupportedFinishings(value []PrintFinishing)()
    SetSupportedMediaColors(value []string)()
    SetSupportedMediaSizes(value []string)()
    SetSupportedMediaTypes(value []PrintMediaType)()
    SetSupportedOrientations(value []PrintOrientation)()
    SetSupportedOutputBins(value []string)()
    SetSupportedPagesPerSheet(value IntegerRangeable)()
    SetSupportedPresentationDirections(value []PrintPresentationDirection)()
    SetSupportedPrintQualities(value []PrintQuality)()
    SetSupportsFitPdfToPage(value *bool)()
    SetTopMargins(value []int32)()
}
