package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatPostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatPostResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatPostResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatPostResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatResponse(), nil
}
// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatPostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMessagesForwardToChatPostResponseable
}
