package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaGetResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaGetResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaGetResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaGetResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaGetResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemPlannerPlansItemTasksDeltaGetResponseable
}
