package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemovePostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemoveResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemovePostResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemoveResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemoveResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemoveResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemoveResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemoveResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemovePostResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemovePostResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemoveResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemoveResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemoveResponse(), nil
}
// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemovePostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemoveResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelMembersRemovePostResponseable
}
