package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddPostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddPostResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddPostResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddPostResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddResponse(), nil
}
// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddPostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionPrimaryChannelGetAllMembersAddPostResponseable
}
