package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemovePostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemoveResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemovePostResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemoveResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemoveResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemoveResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemoveResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemoveResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemovePostResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemovePostResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemoveResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemoveResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemoveResponse(), nil
}
// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemovePostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemoveResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersRemovePostResponseable
}
