package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponse 
// Deprecated: This class is obsolete. Use getMemberObjectsPostResponse instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsPostResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsPostResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsPostResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponse(), nil
}
// TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponseable 
// Deprecated: This class is obsolete. Use getMemberObjectsPostResponse instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberObjectsPostResponseable
}
