package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponse 
// Deprecated: This class is obsolete. Use getMemberGroupsPostResponse instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsPostResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsPostResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsPostResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponse(), nil
}
// TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponseable 
// Deprecated: This class is obsolete. Use getMemberGroupsPostResponse instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemGetMemberGroupsPostResponseable
}
