package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddPostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddPostResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddPostResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddPostResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddResponse(), nil
}
// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddPostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemAllMembersAddPostResponseable
}
