package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse 
// Deprecated: This class is obsolete. Use checkMemberGroupsPostResponse instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsPostResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsPostResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsPostResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponse(), nil
}
// TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponseable 
// Deprecated: This class is obsolete. Use checkMemberGroupsPostResponse instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsItemCheckMemberGroupsPostResponseable
}
