package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddPostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddPostResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddPostResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddPostResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddResponse(), nil
}
// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddPostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemGetAllMembersAddPostResponseable
}
