package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemovePostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemoveResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemovePostResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemoveResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemoveResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemoveResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemoveResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemoveResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemovePostResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemovePostResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemoveResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemoveResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemoveResponse(), nil
}
// Deprecated: This class is obsolete. Use TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemovePostResponseable instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemoveResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionChannelsItemMembersRemovePostResponseable
}
