package teamwork

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponse 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponse struct {
    TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaGetResponse
}
// NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponse instantiates a new TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponse and sets the default values.
func NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponse()(*TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponse) {
    m := &TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponse{
        TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaGetResponse: *NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaGetResponse(),
    }
    return m
}
// CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponse(), nil
}
// TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponseable 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TeamTemplatesItemDefinitionsItemTeamDefinitionPermissionGrantsDeltaGetResponseable
}
