package app

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use OnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponseable instead.
type OnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse struct {
    OnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponse
}
// NewOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse instantiates a new OnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse and sets the default values.
func NewOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse()(*OnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse) {
    m := &OnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse{
        OnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponse: *NewOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponse(),
    }
    return m
}
// CreateOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse(), nil
}
// Deprecated: This class is obsolete. Use OnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponseable instead.
type OnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponseable interface {
    OnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
