package app

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use OnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeGetResponseable instead.
type OnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeResponse struct {
    OnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeGetResponse
}
// NewOnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeResponse instantiates a new OnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeResponse and sets the default values.
func NewOnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeResponse()(*OnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeResponse) {
    m := &OnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeResponse{
        OnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeGetResponse: *NewOnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeGetResponse(),
    }
    return m
}
// CreateOnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewOnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeResponse(), nil
}
// Deprecated: This class is obsolete. Use OnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeGetResponseable instead.
type OnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeResponseable interface {
    OnlinemeetingsGetallrecordingsmeetingorganizeruseridmeetingorganizeruseridwithstartdatetimewithenddatetimeGetAllRecordingsmeetingOrganizerUserIdMeetingOrganizerUserIdWithStartDateTimeWithEndDateTimeGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
