package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponse 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponse struct {
    ItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaGetResponse
}
// NewItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponse instantiates a new ItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponse and sets the default values.
func NewItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponse()(*ItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponse) {
    m := &ItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponse{
        ItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaGetResponse: *NewItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponse(), nil
}
// ItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponseable 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaResponseable interface {
    ItemCalendarCalendarViewItemExceptionOccurrencesItemInstancesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
