package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponse 
// Deprecated: This class is obsolete. Use evaluateApplicationPostResponse instead.
type ItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponse struct {
    ItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationPostResponse
}
// NewItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponse instantiates a new ItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponse and sets the default values.
func NewItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponse()(*ItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponse) {
    m := &ItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponse{
        ItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationPostResponse: *NewItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationPostResponse(),
    }
    return m
}
// CreateItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponse(), nil
}
// ItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponseable 
// Deprecated: This class is obsolete. Use evaluateApplicationPostResponse instead.
type ItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationResponseable interface {
    ItemSitesItemInformationProtectionPolicyLabelsEvaluateApplicationPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
