package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesGetResponseable instead.
type ItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesResponse struct {
    ItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesGetResponse
}
// NewItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesResponse instantiates a new ItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesResponse and sets the default values.
func NewItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesResponse()(*ItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesResponse) {
    m := &ItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesResponse{
        ItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesGetResponse: *NewItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesGetResponse(),
    }
    return m
}
// CreateItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesGetResponseable instead.
type ItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesResponseable interface {
    ItemSitesItemContentModelsGetByNameWithModelNameGetAppliedDrivesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
