package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse struct {
    ItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaGetResponse
}
// NewItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse instantiates a new ItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse and sets the default values.
func NewItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse()(*ItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse) {
    m := &ItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse{
        ItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaGetResponse: *NewItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse(), nil
}
// ItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponseable 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponseable interface {
    ItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
