package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalPostResponseable instead.
type ItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalResponse struct {
    ItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalPostResponse
}
// NewItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalResponse instantiates a new ItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalResponse and sets the default values.
func NewItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalResponse()(*ItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalResponse) {
    m := &ItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalResponse{
        ItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalPostResponse: *NewItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalPostResponse(),
    }
    return m
}
// CreateItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalPostResponseable instead.
type ItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalResponseable interface {
    ItemSitesItemInformationProtectionPolicyLabelsEvaluateRemovalPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
