package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaGetResponseable instead.
type ItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaResponse struct {
    ItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaGetResponse
}
// NewItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaResponse instantiates a new ItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaResponse and sets the default values.
func NewItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaResponse()(*ItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaResponse) {
    m := &ItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaResponse{
        ItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaGetResponse: *NewItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaGetResponseable instead.
type ItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaResponseable interface {
    ItemCalendarEventsItemInstancesItemExceptionoccurrencesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
