package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse struct {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponse
}
// NewFileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse instantiates a new FileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse()(*FileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse) {
    m := &FileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse{
        FileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponse: *NewFileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponseable interface {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
