package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse struct {
    FileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponse
}
// NewFileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse instantiates a new FileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse and sets the default values.
func NewFileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse()(*FileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse) {
    m := &FileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse{
        FileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponse: *NewFileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponse(),
    }
    return m
}
// CreateFileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountResponseable interface {
    FileStorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskCommentTaskChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
