package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse struct {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponse
}
// NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse instantiates a new FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse()(*FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse) {
    m := &FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse{
        FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponse: *NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponseable interface {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
