package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse struct {
    FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponse
}
// NewFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse instantiates a new FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse and sets the default values.
func NewFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse()(*FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse) {
    m := &FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse{
        FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponse: *NewFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponse(),
    }
    return m
}
// CreateFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountResponseable interface {
    FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemCommentTaskChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
