package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable instead.
type FilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse struct {
    FilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse
}
// NewFilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse instantiates a new FilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse and sets the default values.
func NewFilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse()(*FilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse) {
    m := &FilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse{
        FilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse: *NewFilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse(),
    }
    return m
}
// CreateFilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable instead.
type FilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseable interface {
    FilestorageDeletedcontainersItemDriveListContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
