package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse struct {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponse
}
// NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse instantiates a new FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse()(*FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse) {
    m := &FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse{
        FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponse: *NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponseable interface {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
