package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountGetResponseable instead.
type FilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountResponse struct {
    FilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountGetResponse
}
// NewFilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountResponse instantiates a new FilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountResponse and sets the default values.
func NewFilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountResponse()(*FilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountResponse) {
    m := &FilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountResponse{
        FilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountGetResponse: *NewFilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountGetResponse(),
    }
    return m
}
// CreateFilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountGetResponseable instead.
type FilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountResponseable interface {
    FilestorageDeletedcontainersItemDriveItemsItemWorkbookTablesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
