package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthResponse struct {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthGetResponse
}
// NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthResponse instantiates a new FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthResponse()(*FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthResponse) {
    m := &FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthResponse{
        FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthGetResponse: *NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthGetResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthResponseable interface {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemImageWithWidthGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
