package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveListItemsDeltaWithTokenGetResponseable instead.
type FileStorageDeletedContainersItemDriveListItemsDeltaWithTokenResponse struct {
    FileStorageDeletedContainersItemDriveListItemsDeltaWithTokenGetResponse
}
// NewFileStorageDeletedContainersItemDriveListItemsDeltaWithTokenResponse instantiates a new FileStorageDeletedContainersItemDriveListItemsDeltaWithTokenResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveListItemsDeltaWithTokenResponse()(*FileStorageDeletedContainersItemDriveListItemsDeltaWithTokenResponse) {
    m := &FileStorageDeletedContainersItemDriveListItemsDeltaWithTokenResponse{
        FileStorageDeletedContainersItemDriveListItemsDeltaWithTokenGetResponse: *NewFileStorageDeletedContainersItemDriveListItemsDeltaWithTokenGetResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveListItemsDeltaWithTokenResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveListItemsDeltaWithTokenResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveListItemsDeltaWithTokenResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveListItemsDeltaWithTokenGetResponseable instead.
type FileStorageDeletedContainersItemDriveListItemsDeltaWithTokenResponseable interface {
    FileStorageDeletedContainersItemDriveListItemsDeltaWithTokenGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
