package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse struct {
    FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponse
}
// NewFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse instantiates a new FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse and sets the default values.
func NewFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse()(*FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse) {
    m := &FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse{
        FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponse: *NewFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponse(),
    }
    return m
}
// CreateFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponseable interface {
    FileStorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
