package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponseable instead.
type FilestorageContainersItemDriveListItemsItemPermissionsItemGrantResponse struct {
    FilestorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponse
}
// NewFilestorageContainersItemDriveListItemsItemPermissionsItemGrantResponse instantiates a new FilestorageContainersItemDriveListItemsItemPermissionsItemGrantResponse and sets the default values.
func NewFilestorageContainersItemDriveListItemsItemPermissionsItemGrantResponse()(*FilestorageContainersItemDriveListItemsItemPermissionsItemGrantResponse) {
    m := &FilestorageContainersItemDriveListItemsItemPermissionsItemGrantResponse{
        FilestorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponse: *NewFilestorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveListItemsItemPermissionsItemGrantResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveListItemsItemPermissionsItemGrantResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveListItemsItemPermissionsItemGrantResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponseable instead.
type FilestorageContainersItemDriveListItemsItemPermissionsItemGrantResponseable interface {
    FilestorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
