package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse struct {
    FilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponse
}
// NewFilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse instantiates a new FilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse and sets the default values.
func NewFilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse()(*FilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse) {
    m := &FilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse{
        FilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponse: *NewFilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponseable interface {
    FilestorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
