package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveSearchwithqSearchWithQGetResponseable instead.
type FilestorageDeletedcontainersItemDriveSearchwithqSearchWithQResponse struct {
    FilestorageDeletedcontainersItemDriveSearchwithqSearchWithQGetResponse
}
// NewFilestorageDeletedcontainersItemDriveSearchwithqSearchWithQResponse instantiates a new FilestorageDeletedcontainersItemDriveSearchwithqSearchWithQResponse and sets the default values.
func NewFilestorageDeletedcontainersItemDriveSearchwithqSearchWithQResponse()(*FilestorageDeletedcontainersItemDriveSearchwithqSearchWithQResponse) {
    m := &FilestorageDeletedcontainersItemDriveSearchwithqSearchWithQResponse{
        FilestorageDeletedcontainersItemDriveSearchwithqSearchWithQGetResponse: *NewFilestorageDeletedcontainersItemDriveSearchwithqSearchWithQGetResponse(),
    }
    return m
}
// CreateFilestorageDeletedcontainersItemDriveSearchwithqSearchWithQResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageDeletedcontainersItemDriveSearchwithqSearchWithQResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageDeletedcontainersItemDriveSearchwithqSearchWithQResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveSearchwithqSearchWithQGetResponseable instead.
type FilestorageDeletedcontainersItemDriveSearchwithqSearchWithQResponseable interface {
    FilestorageDeletedcontainersItemDriveSearchwithqSearchWithQGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
