package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponseable instead.
type FilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse struct {
    FilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponse
}
// NewFilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse instantiates a new FilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse and sets the default values.
func NewFilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse()(*FilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse) {
    m := &FilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse{
        FilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponse: *NewFilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponse(),
    }
    return m
}
// CreateFilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponseable instead.
type FilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponseable interface {
    FilestorageDeletedcontainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
