package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountResponse struct {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountGetResponse
}
// NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountResponse instantiates a new FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountResponse()(*FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountResponse) {
    m := &FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountResponse{
        FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountGetResponse: *NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountGetResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountResponseable interface {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemRowsCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
