package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveListPermissionsItemGrantPostResponseable instead.
type FilestorageDeletedcontainersItemDriveListPermissionsItemGrantResponse struct {
    FilestorageDeletedcontainersItemDriveListPermissionsItemGrantPostResponse
}
// NewFilestorageDeletedcontainersItemDriveListPermissionsItemGrantResponse instantiates a new FilestorageDeletedcontainersItemDriveListPermissionsItemGrantResponse and sets the default values.
func NewFilestorageDeletedcontainersItemDriveListPermissionsItemGrantResponse()(*FilestorageDeletedcontainersItemDriveListPermissionsItemGrantResponse) {
    m := &FilestorageDeletedcontainersItemDriveListPermissionsItemGrantResponse{
        FilestorageDeletedcontainersItemDriveListPermissionsItemGrantPostResponse: *NewFilestorageDeletedcontainersItemDriveListPermissionsItemGrantPostResponse(),
    }
    return m
}
// CreateFilestorageDeletedcontainersItemDriveListPermissionsItemGrantResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageDeletedcontainersItemDriveListPermissionsItemGrantResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageDeletedcontainersItemDriveListPermissionsItemGrantResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveListPermissionsItemGrantPostResponseable instead.
type FilestorageDeletedcontainersItemDriveListPermissionsItemGrantResponseable interface {
    FilestorageDeletedcontainersItemDriveListPermissionsItemGrantPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
