package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantPostResponseable instead.
type FilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantResponse struct {
    FilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantPostResponse
}
// NewFilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantResponse instantiates a new FilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantResponse and sets the default values.
func NewFilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantResponse()(*FilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantResponse) {
    m := &FilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantResponse{
        FilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantPostResponse: *NewFilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantPostResponse(),
    }
    return m
}
// CreateFilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantPostResponseable instead.
type FilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantResponseable interface {
    FilestorageDeletedcontainersItemDriveListItemsItemPermissionsItemGrantPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
