package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponseable instead.
type FilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse struct {
    FilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponse
}
// NewFilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse instantiates a new FilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse and sets the default values.
func NewFilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse()(*FilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse) {
    m := &FilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse{
        FilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponse: *NewFilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponse(),
    }
    return m
}
// CreateFilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponseable instead.
type FilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponseable interface {
    FilestorageDeletedcontainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
