package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponseable instead.
type FileStorageContainersItemDriveListItemsItemPermissionsItemGrantResponse struct {
    FileStorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponse
}
// NewFileStorageContainersItemDriveListItemsItemPermissionsItemGrantResponse instantiates a new FileStorageContainersItemDriveListItemsItemPermissionsItemGrantResponse and sets the default values.
func NewFileStorageContainersItemDriveListItemsItemPermissionsItemGrantResponse()(*FileStorageContainersItemDriveListItemsItemPermissionsItemGrantResponse) {
    m := &FileStorageContainersItemDriveListItemsItemPermissionsItemGrantResponse{
        FileStorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponse: *NewFileStorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponse(),
    }
    return m
}
// CreateFileStorageContainersItemDriveListItemsItemPermissionsItemGrantResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageContainersItemDriveListItemsItemPermissionsItemGrantResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageContainersItemDriveListItemsItemPermissionsItemGrantResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponseable instead.
type FileStorageContainersItemDriveListItemsItemPermissionsItemGrantResponseable interface {
    FileStorageContainersItemDriveListItemsItemPermissionsItemGrantPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
