package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedGetResponseable instead.
type FilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedResponse struct {
    FilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedGetResponse
}
// NewFilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedResponse instantiates a new FilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedResponse and sets the default values.
func NewFilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedResponse()(*FilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedResponse) {
    m := &FilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedResponse{
        FilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedGetResponse: *NewFilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedGetResponse(),
    }
    return m
}
// CreateFilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedGetResponseable instead.
type FilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedResponseable interface {
    FilestorageDeletedcontainersItemDriveListContenttypesItemIspublishedIsPublishedGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
