package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse struct {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponse
}
// NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse instantiates a new FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse()(*FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse) {
    m := &FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse{
        FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponse: *NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponseable interface {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
