package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountResponse struct {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountGetResponse
}
// NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountResponse instantiates a new FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountResponse()(*FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountResponse) {
    m := &FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountResponse{
        FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountGetResponse: *NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountGetResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountResponseable interface {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookTablesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
