package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantPostResponseable instead.
type FileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantResponse struct {
    FileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantPostResponse
}
// NewFileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantResponse instantiates a new FileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantResponse()(*FileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantResponse) {
    m := &FileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantResponse{
        FileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantPostResponse: *NewFileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantPostResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantPostResponseable instead.
type FileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantResponseable interface {
    FileStorageDeletedContainersItemDriveListItemsItemPermissionsItemGrantPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
