package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse struct {
    FileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponse
}
// NewFileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse instantiates a new FileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse and sets the default values.
func NewFileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse()(*FileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse) {
    m := &FileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse{
        FileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponse: *NewFileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponse(),
    }
    return m
}
// CreateFileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountResponseable interface {
    FileStorageContainersItemDriveItemsItemWorkbookCommentsItemTaskChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
