package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse struct {
    FilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponse
}
// NewFilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse instantiates a new FilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse and sets the default values.
func NewFilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse()(*FilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse) {
    m := &FilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse{
        FilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponse: *NewFilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponseable interface {
    FilestorageContainersItemDriveItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
