package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse struct {
    FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponse
}
// NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse instantiates a new FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse and sets the default values.
func NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse()(*FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse) {
    m := &FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse{
        FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponse: *NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountResponseable interface {
    FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTasksItemChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
