package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantPostResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantResponse struct {
    FileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantPostResponse
}
// NewFileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantResponse instantiates a new FileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantResponse()(*FileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantResponse) {
    m := &FileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantResponse{
        FileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantPostResponse: *NewFileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantPostResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantPostResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantResponseable interface {
    FileStorageDeletedContainersItemDriveItemsItemPermissionsItemGrantPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
