package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemSearchWithQGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemSearchWithQResponse struct {
    FileStorageDeletedContainersItemDriveItemsItemSearchWithQGetResponse
}
// NewFileStorageDeletedContainersItemDriveItemsItemSearchWithQResponse instantiates a new FileStorageDeletedContainersItemDriveItemsItemSearchWithQResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveItemsItemSearchWithQResponse()(*FileStorageDeletedContainersItemDriveItemsItemSearchWithQResponse) {
    m := &FileStorageDeletedContainersItemDriveItemsItemSearchWithQResponse{
        FileStorageDeletedContainersItemDriveItemsItemSearchWithQGetResponse: *NewFileStorageDeletedContainersItemDriveItemsItemSearchWithQGetResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveItemsItemSearchWithQResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveItemsItemSearchWithQResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveItemsItemSearchWithQResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemSearchWithQGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemSearchWithQResponseable interface {
    FileStorageDeletedContainersItemDriveItemsItemSearchWithQGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
