package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthResponse struct {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthGetResponse
}
// NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthResponse instantiates a new FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthResponse and sets the default values.
func NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthResponse()(*FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthResponse) {
    m := &FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthResponse{
        FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthGetResponse: *NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthGetResponse(),
    }
    return m
}
// CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthGetResponseable instead.
type FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthResponseable interface {
    FileStorageDeletedContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
