package drives

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponseable instead.
type ItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse struct {
    ItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponse
}
// NewItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse instantiates a new ItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse and sets the default values.
func NewItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse()(*ItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse) {
    m := &ItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse{
        ItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponse: *NewItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponse(),
    }
    return m
}
// CreateItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponseable instead.
type ItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountResponseable interface {
    ItemItemsItemWorkbookCommentsItemRepliesItemTaskChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
