package drives

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponse 
// Deprecated: This class is obsolete. Use countGetResponse instead.
type ItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponse struct {
    ItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountGetResponse
}
// NewItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponse instantiates a new ItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponse and sets the default values.
func NewItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponse()(*ItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponse) {
    m := &ItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponse{
        ItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountGetResponse: *NewItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountGetResponse(),
    }
    return m
}
// CreateItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponse(), nil
}
// ItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponseable 
// Deprecated: This class is obsolete. Use countGetResponse instead.
type ItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountResponseable interface {
    ItemItemsItemWorkbookCommentsItemTaskCommentRepliesItemTaskChangesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
