package admin

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use WindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberGetResponseable instead.
type WindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberResponse struct {
    WindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberGetResponse
}
// NewWindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberResponse instantiates a new WindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberResponse and sets the default values.
func NewWindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberResponse()(*WindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberResponse) {
    m := &WindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberResponse{
        WindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberGetResponse: *NewWindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberGetResponse(),
    }
    return m
}
// CreateWindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateWindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewWindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberResponse(), nil
}
// Deprecated: This class is obsolete. Use WindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberGetResponseable instead.
type WindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    WindowsUpdatesProductsMicrosoftGraphWindowsUpdatesFindByKbNumberWithKbNumberFindByKbNumberWithKbNumberGetResponseable
}
