package tenantadmin

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    ie233ee762e29b4ba6970aa2a2efce4b7fde11697ca9ea81099d0f8269309c1be "github.com/microsoftgraph/msgraph-beta-sdk-go/models"
)

// Settingsable 
type Settingsable interface {
    ie233ee762e29b4ba6970aa2a2efce4b7fde11697ca9ea81099d0f8269309c1be.Entityable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAllowedDomainGuidsForSyncApp()([]string)
    GetAvailableManagedPathsForSiteCreation()([]string)
    GetDeletedUserPersonalSiteRetentionPeriodInDays()(*int32)
    GetExcludedFileExtensionsForSyncApp()([]string)
    GetImageTaggingOption()(*ImageTaggingChoice)
    GetIsCommentingOnSitePagesEnabled()(*bool)
    GetIsFileActivityNotificationEnabled()(*bool)
    GetIsLoopEnabled()(*bool)
    GetIsMacSyncAppEnabled()(*bool)
    GetIsResharingByExternalUsersEnabled()(*bool)
    GetIsSharePointMobileNotificationEnabled()(*bool)
    GetIsSharePointNewsfeedEnabled()(*bool)
    GetIsSiteCreationEnabled()(*bool)
    GetIsSiteCreationUIEnabled()(*bool)
    GetIsSitePagesCreationEnabled()(*bool)
    GetIsSitesStorageLimitAutomatic()(*bool)
    GetIsSyncButtonHiddenOnPersonalSite()(*bool)
    GetIsUnmanagedSyncAppForTenantRestricted()(*bool)
    GetPersonalSiteDefaultStorageLimitInMB()(*int64)
    GetSharingAllowedDomainList()([]string)
    GetSharingBlockedDomainList()([]string)
    GetSharingCapability()(*SharingCapabilities)
    GetSharingDomainRestrictionMode()(*SharingDomainRestrictionMode)
    GetSiteCreationDefaultManagedPath()(*string)
    GetSiteCreationDefaultStorageLimitInMB()(*int32)
    GetTenantDefaultTimezone()(*string)
    SetAllowedDomainGuidsForSyncApp(value []string)()
    SetAvailableManagedPathsForSiteCreation(value []string)()
    SetDeletedUserPersonalSiteRetentionPeriodInDays(value *int32)()
    SetExcludedFileExtensionsForSyncApp(value []string)()
    SetImageTaggingOption(value *ImageTaggingChoice)()
    SetIsCommentingOnSitePagesEnabled(value *bool)()
    SetIsFileActivityNotificationEnabled(value *bool)()
    SetIsLoopEnabled(value *bool)()
    SetIsMacSyncAppEnabled(value *bool)()
    SetIsResharingByExternalUsersEnabled(value *bool)()
    SetIsSharePointMobileNotificationEnabled(value *bool)()
    SetIsSharePointNewsfeedEnabled(value *bool)()
    SetIsSiteCreationEnabled(value *bool)()
    SetIsSiteCreationUIEnabled(value *bool)()
    SetIsSitePagesCreationEnabled(value *bool)()
    SetIsSitesStorageLimitAutomatic(value *bool)()
    SetIsSyncButtonHiddenOnPersonalSite(value *bool)()
    SetIsUnmanagedSyncAppForTenantRestricted(value *bool)()
    SetPersonalSiteDefaultStorageLimitInMB(value *int64)()
    SetSharingAllowedDomainList(value []string)()
    SetSharingBlockedDomainList(value []string)()
    SetSharingCapability(value *SharingCapabilities)()
    SetSharingDomainRestrictionMode(value *SharingDomainRestrictionMode)()
    SetSiteCreationDefaultManagedPath(value *string)()
    SetSiteCreationDefaultStorageLimitInMB(value *int32)()
    SetTenantDefaultTimezone(value *string)()
}
