package tenantrelationships

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchPostResponseable instead.
type ManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchResponse struct {
    ManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchPostResponse
}
// NewManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchResponse instantiates a new ManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchResponse and sets the default values.
func NewManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchResponse()(*ManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchResponse) {
    m := &ManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchResponse{
        ManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchPostResponse: *NewManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchPostResponse(),
    }
    return m
}
// CreateManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchResponse(), nil
}
// Deprecated: This class is obsolete. Use ManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchPostResponseable instead.
type ManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchResponseable interface {
    ManagedtenantsTenantgroupsMicrosoftgraphmanagedtenantstenantsearchTenantSearchPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
