package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponseable instead.
type ItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse struct {
    ItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponse
}
// NewItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse instantiates a new ItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse and sets the default values.
func NewItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse()(*ItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse) {
    m := &ItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse{
        ItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponse: *NewItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponseable instead.
type ItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponseable interface {
    ItemCalendargroupsItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
