package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponseable instead.
type ItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse struct {
    ItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponse
}
// NewItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse instantiates a new ItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse and sets the default values.
func NewItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse()(*ItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse) {
    m := &ItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse{
        ItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponse: *NewItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponse(),
    }
    return m
}
// CreateItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponseable instead.
type ItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlResponseable interface {
    ItemOnlineMeetingsWithJoinWebUrlGetVirtualAppointmentJoinWebUrlGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
