package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompletePostResponseable instead.
type ItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompleteResponse struct {
    ItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompletePostResponse
}
// NewItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompleteResponse instantiates a new ItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompleteResponse and sets the default values.
func NewItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompleteResponse()(*ItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompleteResponse) {
    m := &ItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompleteResponse{
        ItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompletePostResponse: *NewItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompletePostResponse(),
    }
    return m
}
// CreateItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompleteResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompleteResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompleteResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompletePostResponseable instead.
type ItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompleteResponseable interface {
    ItemOutlookTaskGroupsItemTaskFoldersItemTasksItemCompletePostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
