package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaGetResponseable instead.
type ItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaResponse struct {
    ItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaGetResponse
}
// NewItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaResponse instantiates a new ItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaResponse and sets the default values.
func NewItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaResponse()(*ItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaResponse) {
    m := &ItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaResponse{
        ItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaGetResponse: *NewItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaGetResponseable instead.
type ItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaResponseable interface {
    ItemCalendargroupsItemCalendarsItemCalendarviewItemExceptionoccurrencesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
