package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type ItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    ItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new ItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*ItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &ItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        ItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type ItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    ItemPendingaccessreviewinstancesItemStagesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
