package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponseable instead.
type ItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse struct {
    ItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponse
}
// NewItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse instantiates a new ItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse and sets the default values.
func NewItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse()(*ItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse) {
    m := &ItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse{
        ItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponse: *NewItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponseable instead.
type ItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaResponseable interface {
    ItemCalendarsItemEventsItemInstancesItemExceptionoccurrencesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
