package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaGetResponseable instead.
type ItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaResponse struct {
    ItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaGetResponse
}
// NewItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaResponse instantiates a new ItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaResponse and sets the default values.
func NewItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaResponse()(*ItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaResponse) {
    m := &ItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaResponse{
        ItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaGetResponse: *NewItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaGetResponseable instead.
type ItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaResponseable interface {
    ItemCalendarCalendarviewItemExceptionoccurrencesItemInstancesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
