package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponse 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type ItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponse struct {
    ItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnGetResponse
}
// NewItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponse instantiates a new ItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponse and sets the default values.
func NewItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponse()(*ItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponse) {
    m := &ItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponse{
        ItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnGetResponse: *NewItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponse(), nil
}
// ItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponseable 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type ItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnResponseable interface {
    ItemAppConsentRequestsForApprovalFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
