package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemPendingAccessReviewInstancesFilterByCurrentUserWithOnGetResponseable instead.
type ItemPendingAccessReviewInstancesFilterByCurrentUserWithOnResponse struct {
    ItemPendingAccessReviewInstancesFilterByCurrentUserWithOnGetResponse
}
// NewItemPendingAccessReviewInstancesFilterByCurrentUserWithOnResponse instantiates a new ItemPendingAccessReviewInstancesFilterByCurrentUserWithOnResponse and sets the default values.
func NewItemPendingAccessReviewInstancesFilterByCurrentUserWithOnResponse()(*ItemPendingAccessReviewInstancesFilterByCurrentUserWithOnResponse) {
    m := &ItemPendingAccessReviewInstancesFilterByCurrentUserWithOnResponse{
        ItemPendingAccessReviewInstancesFilterByCurrentUserWithOnGetResponse: *NewItemPendingAccessReviewInstancesFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateItemPendingAccessReviewInstancesFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemPendingAccessReviewInstancesFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemPendingAccessReviewInstancesFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemPendingAccessReviewInstancesFilterByCurrentUserWithOnGetResponseable instead.
type ItemPendingAccessReviewInstancesFilterByCurrentUserWithOnResponseable interface {
    ItemPendingAccessReviewInstancesFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
