package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompletePostResponseable instead.
type ItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompleteResponse struct {
    ItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompletePostResponse
}
// NewItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompleteResponse instantiates a new ItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompleteResponse and sets the default values.
func NewItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompleteResponse()(*ItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompleteResponse) {
    m := &ItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompleteResponse{
        ItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompletePostResponse: *NewItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompletePostResponse(),
    }
    return m
}
// CreateItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompleteResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompleteResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompleteResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompletePostResponseable instead.
type ItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompleteResponseable interface {
    ItemOutlookTaskgroupsItemTaskfoldersItemTasksItemCompletePostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
