package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsPostResponseable instead.
type ItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsResponse struct {
    ItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsPostResponse
}
// NewItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsResponse instantiates a new ItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsResponse and sets the default values.
func NewItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsResponse()(*ItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsResponse) {
    m := &ItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsResponse{
        ItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsPostResponse: *NewItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsPostResponse(),
    }
    return m
}
// CreateItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsPostResponseable instead.
type ItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsResponseable interface {
    ItemGetpasswordsinglesignoncredentialsGetPasswordSingleSignOnCredentialsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
