package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponse 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponse struct {
    ItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaGetResponse
}
// NewItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponse instantiates a new ItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponse and sets the default values.
func NewItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponse()(*ItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponse) {
    m := &ItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponse{
        ItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaGetResponse: *NewItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponse(), nil
}
// ItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponseable 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaResponseable interface {
    ItemCalendarGroupsItemCalendarsItemEventsItemInstancesItemExceptionOccurrencesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
