package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponse 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponse struct {
    ItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaGetResponse
}
// NewItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponse instantiates a new ItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponse and sets the default values.
func NewItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponse()(*ItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponse) {
    m := &ItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponse{
        ItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaGetResponse: *NewItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponse(), nil
}
// ItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponseable 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaResponseable interface {
    ItemCalendarGroupsItemCalendarsItemCalendarViewItemExceptionOccurrencesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
