package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type ItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    ItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new ItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*ItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &ItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        ItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type ItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    ItemPendingaccessreviewinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
