package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsGetResponseable instead.
type ItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsResponse struct {
    ItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsGetResponse
}
// NewItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsResponse instantiates a new ItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsResponse and sets the default values.
func NewItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsResponse()(*ItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsResponse) {
    m := &ItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsResponse{
        ItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsGetResponse: *NewItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsGetResponse(),
    }
    return m
}
// CreateItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsGetResponseable instead.
type ItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsResponseable interface {
    ItemGeteffectivedeviceenrollmentconfigurationsGetEffectiveDeviceEnrollmentConfigurationsGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
