package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaGetResponseable instead.
type ItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaResponse struct {
    ItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaGetResponse
}
// NewItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaResponse instantiates a new ItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaResponse and sets the default values.
func NewItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaResponse()(*ItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaResponse) {
    m := &ItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaResponse{
        ItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaGetResponse: *NewItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaGetResponseable instead.
type ItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaResponseable interface {
    ItemCalendarsItemCalendarviewItemInstancesItemExceptionoccurrencesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
