package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaGetResponseable instead.
type ItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaResponse struct {
    ItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaGetResponse
}
// NewItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaResponse instantiates a new ItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaResponse and sets the default values.
func NewItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaResponse()(*ItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaResponse) {
    m := &ItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaResponse{
        ItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaGetResponse: *NewItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaGetResponseable instead.
type ItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaResponseable interface {
    ItemCalendarsItemEventsItemExceptionoccurrencesItemInstancesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
