package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse struct {
    ItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaGetResponse
}
// NewItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse instantiates a new ItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse and sets the default values.
func NewItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse()(*ItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse) {
    m := &ItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse{
        ItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaGetResponse: *NewItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponse(), nil
}
// ItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponseable 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaResponseable interface {
    ItemCalendarsItemCalendarViewItemInstancesItemExceptionOccurrencesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
