package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponse 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponse struct {
    ItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaGetResponse
}
// NewItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponse instantiates a new ItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponse and sets the default values.
func NewItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponse()(*ItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponse) {
    m := &ItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponse{
        ItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaGetResponse: *NewItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponse(), nil
}
// ItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponseable 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type ItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaResponseable interface {
    ItemCalendarGroupsItemCalendarsItemEventsItemExceptionOccurrencesItemInstancesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
