package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemInformationProtectionPolicyLabelsEvaluateApplicationPostResponseable instead.
type ItemInformationProtectionPolicyLabelsEvaluateApplicationResponse struct {
    ItemInformationProtectionPolicyLabelsEvaluateApplicationPostResponse
}
// NewItemInformationProtectionPolicyLabelsEvaluateApplicationResponse instantiates a new ItemInformationProtectionPolicyLabelsEvaluateApplicationResponse and sets the default values.
func NewItemInformationProtectionPolicyLabelsEvaluateApplicationResponse()(*ItemInformationProtectionPolicyLabelsEvaluateApplicationResponse) {
    m := &ItemInformationProtectionPolicyLabelsEvaluateApplicationResponse{
        ItemInformationProtectionPolicyLabelsEvaluateApplicationPostResponse: *NewItemInformationProtectionPolicyLabelsEvaluateApplicationPostResponse(),
    }
    return m
}
// CreateItemInformationProtectionPolicyLabelsEvaluateApplicationResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemInformationProtectionPolicyLabelsEvaluateApplicationResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemInformationProtectionPolicyLabelsEvaluateApplicationResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemInformationProtectionPolicyLabelsEvaluateApplicationPostResponseable instead.
type ItemInformationProtectionPolicyLabelsEvaluateApplicationResponseable interface {
    ItemInformationProtectionPolicyLabelsEvaluateApplicationPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
