package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponseable instead.
type ItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse struct {
    ItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponse
}
// NewItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse instantiates a new ItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse and sets the default values.
func NewItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse()(*ItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse) {
    m := &ItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse{
        ItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponse: *NewItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponse(),
    }
    return m
}
// CreateItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponseable instead.
type ItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponseable interface {
    ItemManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
