package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponseable instead.
type ItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse struct {
    ItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponse
}
// NewItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse instantiates a new ItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse and sets the default values.
func NewItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse()(*ItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse) {
    m := &ItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse{
        ItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponse: *NewItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponse(),
    }
    return m
}
// CreateItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponseable instead.
type ItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponseable interface {
    ItemCloudPCsGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
