package users

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i20a3050780ee0b0cde0a884a4f35429a20d60067e3bcda382ec5400079147459 "github.com/microsoftgraph/msgraph-beta-sdk-go/models/odataerrors"
)

// ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder provides operations to call the removeDeviceFirmwareConfigurationInterfaceManagement method.
type ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilderInternal instantiates a new ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder and sets the default values.
func NewItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder) {
    m := &ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/users/{user%2Did}/managedDevices/{managedDevice%2Did}/removeDeviceFirmwareConfigurationInterfaceManagement", pathParameters),
    }
    return m
}
// NewItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder instantiates a new ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder and sets the default values.
func NewItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilderInternal(urlParams, requestAdapter)
}
// Post remove device from Device Firmware Configuration Interface management
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder) Post(ctx context.Context, requestConfiguration *ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilderPostRequestConfiguration)(error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": i20a3050780ee0b0cde0a884a4f35429a20d60067e3bcda382ec5400079147459.CreateODataErrorFromDiscriminatorValue,
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
    if err != nil {
        return err
    }
    return nil
}
// ToPostRequestInformation remove device from Device Firmware Configuration Interface management
// returns a *RequestInformation when successful
func (m *ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder when successful
func (m *ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder) WithUrl(rawUrl string)(*ItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder) {
    return NewItemManageddevicesItemRemovedevicefirmwareconfigurationinterfacemanagementRemoveDeviceFirmwareConfigurationInterfaceManagementRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
