package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryGetResponseable instead.
type ItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryResponse struct {
    ItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryGetResponse
}
// NewItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryResponse instantiates a new ItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryResponse and sets the default values.
func NewItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryResponse()(*ItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryResponse) {
    m := &ItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryResponse{
        ItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryGetResponse: *NewItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryGetResponse(),
    }
    return m
}
// CreateItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryGetResponseable instead.
type ItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryResponseable interface {
    ItemCloudpcsItemGetcloudpcconnectivityhistoryGetCloudPcConnectivityHistoryGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
