package communications

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use CallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeGetResponseable instead.
type CallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeResponse struct {
    CallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeGetResponse
}
// NewCallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeResponse instantiates a new CallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeResponse and sets the default values.
func NewCallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeResponse()(*CallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeResponse) {
    m := &CallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeResponse{
        CallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeGetResponse: *NewCallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeGetResponse(),
    }
    return m
}
// CreateCallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeResponse(), nil
}
// Deprecated: This class is obsolete. Use CallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeGetResponseable instead.
type CallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeResponseable interface {
    CallrecordsMicrosoftgraphcallrecordsgetpstnblockeduserslogwithfromdatetimewithtodatetimeGetPstnBlockedUsersLogWithFromDateTimeWithToDateTimeGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
