package communications

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use CallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeGetResponseable instead.
type CallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeResponse struct {
    CallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeGetResponse
}
// NewCallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeResponse instantiates a new CallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeResponse and sets the default values.
func NewCallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeResponse()(*CallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeResponse) {
    m := &CallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeResponse{
        CallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeGetResponse: *NewCallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeGetResponse(),
    }
    return m
}
// CreateCallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeResponse(), nil
}
// Deprecated: This class is obsolete. Use CallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeGetResponseable instead.
type CallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeResponseable interface {
    CallrecordsMicrosoftgraphcallrecordsgetpstnonlinemeetingdialoutreportwithfromdatetimewithtodatetimeGetPstnOnlineMeetingDialoutReportWithFromDateTimeWithToDateTimeGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
