package managedtenants
import (
    "strings"
    "errors"
)
// 
type ManagementTemplateDeploymentStatus int

const (
    TOADDRESS_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS ManagementTemplateDeploymentStatus = iota
    COMPLETED_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS
    ERROR_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS
    TIMEOUT_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS
    INPROGRESS_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS
    PLANNED_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS
    RESOLVEDBY3RDPARTY_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS
    RESOLVEDTHROUGHALTERNATEMITIGATION_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS
    RISKACCEPTED_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS
    UNKNOWNFUTUREVALUE_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS
)

func (i ManagementTemplateDeploymentStatus) String() string {
    return []string{"TOADDRESS", "COMPLETED", "ERROR", "TIMEOUT", "INPROGRESS", "PLANNED", "RESOLVEDBY3RDPARTY", "RESOLVEDTHROUGHALTERNATEMITIGATION", "RISKACCEPTED", "UNKNOWNFUTUREVALUE"}[i]
}
func ParseManagementTemplateDeploymentStatus(v string) (interface{}, error) {
    switch strings.ToUpper(v) {
        case "TOADDRESS":
            return TOADDRESS_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS, nil
        case "COMPLETED":
            return COMPLETED_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS, nil
        case "ERROR":
            return ERROR_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS, nil
        case "TIMEOUT":
            return TIMEOUT_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS, nil
        case "INPROGRESS":
            return INPROGRESS_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS, nil
        case "PLANNED":
            return PLANNED_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS, nil
        case "RESOLVEDBY3RDPARTY":
            return RESOLVEDBY3RDPARTY_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS, nil
        case "RESOLVEDTHROUGHALTERNATEMITIGATION":
            return RESOLVEDTHROUGHALTERNATEMITIGATION_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS, nil
        case "RISKACCEPTED":
            return RISKACCEPTED_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS, nil
        case "UNKNOWNFUTUREVALUE":
            return UNKNOWNFUTUREVALUE_MANAGEMENTTEMPLATEDEPLOYMENTSTATUS, nil
    }
    return 0, errors.New("Unknown ManagementTemplateDeploymentStatus value: " + v)
}
func SerializeManagementTemplateDeploymentStatus(values []ManagementTemplateDeploymentStatus) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
