package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponse 
// Deprecated: This class is obsolete. Use requestSignupUrlPostResponse instead.
type AndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponse struct {
    AndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlPostResponse
}
// NewAndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponse instantiates a new AndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponse and sets the default values.
func NewAndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponse()(*AndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponse) {
    m := &AndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponse{
        AndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlPostResponse: *NewAndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlPostResponse(),
    }
    return m
}
// CreateAndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateAndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponse(), nil
}
// AndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponseable 
// Deprecated: This class is obsolete. Use requestSignupUrlPostResponse instead.
type AndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlResponseable interface {
    AndroidManagedStoreAccountEnterpriseSettingsRequestSignupUrlPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
