package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponse 
// Deprecated: This class is obsolete. Use createGooglePlayWebTokenPostResponse instead.
type AndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponse struct {
    AndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenPostResponse
}
// NewAndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponse instantiates a new AndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponse and sets the default values.
func NewAndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponse()(*AndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponse) {
    m := &AndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponse{
        AndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenPostResponse: *NewAndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenPostResponse(),
    }
    return m
}
// CreateAndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateAndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponse(), nil
}
// AndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponseable 
// Deprecated: This class is obsolete. Use createGooglePlayWebTokenPostResponse instead.
type AndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenResponseable interface {
    AndroidManagedStoreAccountEnterpriseSettingsCreateGooglePlayWebTokenPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
