package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlPostResponseable instead.
type AndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlResponse struct {
    AndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlPostResponse
}
// NewAndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlResponse instantiates a new AndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlResponse and sets the default values.
func NewAndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlResponse()(*AndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlResponse) {
    m := &AndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlResponse{
        AndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlPostResponse: *NewAndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlPostResponse(),
    }
    return m
}
// CreateAndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlResponse(), nil
}
// Deprecated: This class is obsolete. Use AndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlPostResponseable instead.
type AndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlResponseable interface {
    AndroidmanagedstoreaccountenterprisesettingsRequestsignupurlRequestSignupUrlPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
