package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AndroidforworksettingsRequestsignupurlRequestSignupUrlPostResponseable instead.
type AndroidforworksettingsRequestsignupurlRequestSignupUrlResponse struct {
    AndroidforworksettingsRequestsignupurlRequestSignupUrlPostResponse
}
// NewAndroidforworksettingsRequestsignupurlRequestSignupUrlResponse instantiates a new AndroidforworksettingsRequestsignupurlRequestSignupUrlResponse and sets the default values.
func NewAndroidforworksettingsRequestsignupurlRequestSignupUrlResponse()(*AndroidforworksettingsRequestsignupurlRequestSignupUrlResponse) {
    m := &AndroidforworksettingsRequestsignupurlRequestSignupUrlResponse{
        AndroidforworksettingsRequestsignupurlRequestSignupUrlPostResponse: *NewAndroidforworksettingsRequestsignupurlRequestSignupUrlPostResponse(),
    }
    return m
}
// CreateAndroidforworksettingsRequestsignupurlRequestSignupUrlResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAndroidforworksettingsRequestsignupurlRequestSignupUrlResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAndroidforworksettingsRequestsignupurlRequestSignupUrlResponse(), nil
}
// Deprecated: This class is obsolete. Use AndroidforworksettingsRequestsignupurlRequestSignupUrlPostResponseable instead.
type AndroidforworksettingsRequestsignupurlRequestSignupUrlResponseable interface {
    AndroidforworksettingsRequestsignupurlRequestSignupUrlPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
