package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponse 
// Deprecated: This class is obsolete. Use getPlatformSupportedPropertiesWithPlatformGetResponse instead.
type AssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponse struct {
    AssignmentFiltersGetPlatformSupportedPropertiesWithPlatformGetResponse
}
// NewAssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponse instantiates a new AssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponse and sets the default values.
func NewAssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponse()(*AssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponse) {
    m := &AssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponse{
        AssignmentFiltersGetPlatformSupportedPropertiesWithPlatformGetResponse: *NewAssignmentFiltersGetPlatformSupportedPropertiesWithPlatformGetResponse(),
    }
    return m
}
// CreateAssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateAssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponse(), nil
}
// AssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponseable 
// Deprecated: This class is obsolete. Use getPlatformSupportedPropertiesWithPlatformGetResponse instead.
type AssignmentFiltersGetPlatformSupportedPropertiesWithPlatformResponseable interface {
    AssignmentFiltersGetPlatformSupportedPropertiesWithPlatformGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
