package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use CertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesPostResponseable instead.
type CertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesResponse struct {
    CertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesPostResponse
}
// NewCertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesResponse instantiates a new CertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesResponse and sets the default values.
func NewCertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesResponse()(*CertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesResponse) {
    m := &CertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesResponse{
        CertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesPostResponse: *NewCertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesPostResponse(),
    }
    return m
}
// CreateCertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesResponse(), nil
}
// Deprecated: This class is obsolete. Use CertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesPostResponseable instead.
type CertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesResponseable interface {
    CertificateconnectordetailsItemGethealthmetrictimeseriesGetHealthMetricTimeSeriesPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
