package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use CloudCertificationAuthorityItemPostCloudCertificationAuthorityPostResponseable instead.
type CloudCertificationAuthorityItemPostCloudCertificationAuthorityResponse struct {
    CloudCertificationAuthorityItemPostCloudCertificationAuthorityPostResponse
}
// NewCloudCertificationAuthorityItemPostCloudCertificationAuthorityResponse instantiates a new CloudCertificationAuthorityItemPostCloudCertificationAuthorityResponse and sets the default values.
func NewCloudCertificationAuthorityItemPostCloudCertificationAuthorityResponse()(*CloudCertificationAuthorityItemPostCloudCertificationAuthorityResponse) {
    m := &CloudCertificationAuthorityItemPostCloudCertificationAuthorityResponse{
        CloudCertificationAuthorityItemPostCloudCertificationAuthorityPostResponse: *NewCloudCertificationAuthorityItemPostCloudCertificationAuthorityPostResponse(),
    }
    return m
}
// CreateCloudCertificationAuthorityItemPostCloudCertificationAuthorityResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCloudCertificationAuthorityItemPostCloudCertificationAuthorityResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCloudCertificationAuthorityItemPostCloudCertificationAuthorityResponse(), nil
}
// Deprecated: This class is obsolete. Use CloudCertificationAuthorityItemPostCloudCertificationAuthorityPostResponseable instead.
type CloudCertificationAuthorityItemPostCloudCertificationAuthorityResponseable interface {
    CloudCertificationAuthorityItemPostCloudCertificationAuthorityPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
