package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use CompliancepoliciesItemSetscheduledactionsSetScheduledActionsPostResponseable instead.
type CompliancepoliciesItemSetscheduledactionsSetScheduledActionsResponse struct {
    CompliancepoliciesItemSetscheduledactionsSetScheduledActionsPostResponse
}
// NewCompliancepoliciesItemSetscheduledactionsSetScheduledActionsResponse instantiates a new CompliancepoliciesItemSetscheduledactionsSetScheduledActionsResponse and sets the default values.
func NewCompliancepoliciesItemSetscheduledactionsSetScheduledActionsResponse()(*CompliancepoliciesItemSetscheduledactionsSetScheduledActionsResponse) {
    m := &CompliancepoliciesItemSetscheduledactionsSetScheduledActionsResponse{
        CompliancepoliciesItemSetscheduledactionsSetScheduledActionsPostResponse: *NewCompliancepoliciesItemSetscheduledactionsSetScheduledActionsPostResponse(),
    }
    return m
}
// CreateCompliancepoliciesItemSetscheduledactionsSetScheduledActionsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCompliancepoliciesItemSetscheduledactionsSetScheduledActionsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCompliancepoliciesItemSetscheduledactionsSetScheduledActionsResponse(), nil
}
// Deprecated: This class is obsolete. Use CompliancepoliciesItemSetscheduledactionsSetScheduledActionsPostResponseable instead.
type CompliancepoliciesItemSetscheduledactionsSetScheduledActionsResponseable interface {
    CompliancepoliciesItemSetscheduledactionsSetScheduledActionsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
