package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetPostResponseable instead.
type ConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetResponse struct {
    ConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetPostResponse
}
// NewConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetResponse instantiates a new ConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetResponse and sets the default values.
func NewConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetResponse()(*ConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetResponse) {
    m := &ConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetResponse{
        ConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetPostResponse: *NewConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetPostResponse(),
    }
    return m
}
// CreateConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetResponse(), nil
}
// Deprecated: This class is obsolete. Use ConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetPostResponseable instead.
type ConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetResponseable interface {
    ConfigurationPoliciesItemClearEnrollmentTimeDeviceMembershipTargetPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
