package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponseable instead.
type ConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse struct {
    ConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponse
}
// NewConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse instantiates a new ConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse and sets the default values.
func NewConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse()(*ConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse) {
    m := &ConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse{
        ConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponse: *NewConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponse(),
    }
    return m
}
// CreateConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse(), nil
}
// Deprecated: This class is obsolete. Use ConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponseable instead.
type ConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponseable interface {
    ConfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
