package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ConfigurationPoliciesItemAssignJustInTimeConfigurationPostResponseable instead.
type ConfigurationPoliciesItemAssignJustInTimeConfigurationResponse struct {
    ConfigurationPoliciesItemAssignJustInTimeConfigurationPostResponse
}
// NewConfigurationPoliciesItemAssignJustInTimeConfigurationResponse instantiates a new ConfigurationPoliciesItemAssignJustInTimeConfigurationResponse and sets the default values.
func NewConfigurationPoliciesItemAssignJustInTimeConfigurationResponse()(*ConfigurationPoliciesItemAssignJustInTimeConfigurationResponse) {
    m := &ConfigurationPoliciesItemAssignJustInTimeConfigurationResponse{
        ConfigurationPoliciesItemAssignJustInTimeConfigurationPostResponse: *NewConfigurationPoliciesItemAssignJustInTimeConfigurationPostResponse(),
    }
    return m
}
// CreateConfigurationPoliciesItemAssignJustInTimeConfigurationResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateConfigurationPoliciesItemAssignJustInTimeConfigurationResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewConfigurationPoliciesItemAssignJustInTimeConfigurationResponse(), nil
}
// Deprecated: This class is obsolete. Use ConfigurationPoliciesItemAssignJustInTimeConfigurationPostResponseable instead.
type ConfigurationPoliciesItemAssignJustInTimeConfigurationResponseable interface {
    ConfigurationPoliciesItemAssignJustInTimeConfigurationPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
