package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use {TypeName} instead.
type DepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeResponse struct {
    DepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeGetResponse
}
// NewDepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeResponse instantiates a new DepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeResponse and sets the default values.
func NewDepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeResponse()(*DepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeResponse) {
    m := &DepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeResponse{
        DepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeGetResponse: *NewDepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeGetResponse(),
    }
    return m
}
// CreateDepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeResponse(), nil
}
// Deprecated: This class is obsolete. Use {TypeName} instead.
type DepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeResponseable interface {
    DepOnboardingSettingsGetExpiringVppTokenCountWithExpiringBeforeDateTimeGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
