package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use DeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyPostResponseable instead.
type DeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyResponse struct {
    DeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyPostResponse
}
// NewDeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyResponse instantiates a new DeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyResponse and sets the default values.
func NewDeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyResponse()(*DeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyResponse) {
    m := &DeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyResponse{
        DeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyPostResponse: *NewDeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyPostResponse(),
    }
    return m
}
// CreateDeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyResponse(), nil
}
// Deprecated: This class is obsolete. Use DeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyPostResponseable instead.
type DeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyResponseable interface {
    DeponboardingsettingsItemGenerateencryptionpublickeyGenerateEncryptionPublicKeyPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
