package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use DevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireGetResponseable instead.
type DevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireResponse struct {
    DevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireGetResponse
}
// NewDevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireResponse instantiates a new DevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireResponse and sets the default values.
func NewDevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireResponse()(*DevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireResponse) {
    m := &DevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireResponse{
        DevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireGetResponse: *NewDevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireGetResponse(),
    }
    return m
}
// CreateDevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireResponse(), nil
}
// Deprecated: This class is obsolete. Use DevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireGetResponseable instead.
type DevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireResponseable interface {
    DevicecompliancepoliciesGetdevicesscheduledtoretireGetDevicesScheduledToRetireGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
