package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use DeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesPostResponseable instead.
type DeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesResponse struct {
    DeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesPostResponse
}
// NewDeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesResponse instantiates a new DeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesResponse and sets the default values.
func NewDeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesResponse()(*DeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesResponse) {
    m := &DeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesResponse{
        DeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesPostResponse: *NewDeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesPostResponse(),
    }
    return m
}
// CreateDeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesResponse(), nil
}
// Deprecated: This class is obsolete. Use DeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesPostResponseable instead.
type DeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesResponseable interface {
    DeviceconfigurationsGettargetedusersanddevicesGetTargetedUsersAndDevicesPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
