package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use DevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptPostResponseable instead.
type DevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptResponse struct {
    DevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptPostResponse
}
// NewDevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptResponse instantiates a new DevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptResponse and sets the default values.
func NewDevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptResponse()(*DevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptResponse) {
    m := &DevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptResponse{
        DevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptPostResponse: *NewDevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptPostResponse(),
    }
    return m
}
// CreateDevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptResponse(), nil
}
// Deprecated: This class is obsolete. Use DevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptPostResponseable instead.
type DevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptResponseable interface {
    DevicehealthscriptsItemUpdateglobalscriptUpdateGlobalScriptPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
