package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportPostResponseable instead.
type GrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportResponse struct {
    GrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportPostResponse
}
// NewGrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportResponse instantiates a new GrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportResponse and sets the default values.
func NewGrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportResponse()(*GrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportResponse) {
    m := &GrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportResponse{
        GrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportPostResponse: *NewGrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportPostResponse(),
    }
    return m
}
// CreateGrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportResponse(), nil
}
// Deprecated: This class is obsolete. Use GrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportPostResponseable instead.
type GrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportResponseable interface {
    GrouppolicymigrationreportsCreatemigrationreportCreateMigrationReportPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
