package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponseable instead.
type ManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse struct {
    ManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponse
}
// NewManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse instantiates a new ManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse and sets the default values.
func NewManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse()(*ManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse) {
    m := &ManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse{
        ManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponse: *NewManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponse(),
    }
    return m
}
// CreateManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponse(), nil
}
// Deprecated: This class is obsolete. Use ManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponseable instead.
type ManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsResponseable interface {
    ManagedDevicesItemLogCollectionRequestsItemDownloadDeviceLogsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
