// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package devicemanagement

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i20a3050780ee0b0cde0a884a4f35429a20d60067e3bcda382ec5400079147459 "github.com/microsoftgraph/msgraph-beta-sdk-go/models/odataerrors"
)

// ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder provides operations to call the suspendManagedHomeScreen method.
type ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ManagedDevicesItemSuspendManagedHomeScreenRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type ManagedDevicesItemSuspendManagedHomeScreenRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewManagedDevicesItemSuspendManagedHomeScreenRequestBuilderInternal instantiates a new ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder and sets the default values.
func NewManagedDevicesItemSuspendManagedHomeScreenRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder) {
    m := &ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/deviceManagement/managedDevices/{managedDevice%2Did}/suspendManagedHomeScreen", pathParameters),
    }
    return m
}
// NewManagedDevicesItemSuspendManagedHomeScreenRequestBuilder instantiates a new ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder and sets the default values.
func NewManagedDevicesItemSuspendManagedHomeScreenRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewManagedDevicesItemSuspendManagedHomeScreenRequestBuilderInternal(urlParams, requestAdapter)
}
// Post temporarily suspend Managed Home Screen
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder) Post(ctx context.Context, body ManagedDevicesItemSuspendManagedHomeScreenPostRequestBodyable, requestConfiguration *ManagedDevicesItemSuspendManagedHomeScreenRequestBuilderPostRequestConfiguration)(error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": i20a3050780ee0b0cde0a884a4f35429a20d60067e3bcda382ec5400079147459.CreateODataErrorFromDiscriminatorValue,
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
    if err != nil {
        return err
    }
    return nil
}
// ToPostRequestInformation temporarily suspend Managed Home Screen
// returns a *RequestInformation when successful
func (m *ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder) ToPostRequestInformation(ctx context.Context, body ManagedDevicesItemSuspendManagedHomeScreenPostRequestBodyable, requestConfiguration *ManagedDevicesItemSuspendManagedHomeScreenRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder when successful
func (m *ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder) WithUrl(rawUrl string)(*ManagedDevicesItemSuspendManagedHomeScreenRequestBuilder) {
    return NewManagedDevicesItemSuspendManagedHomeScreenRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
