package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesGetResponseable instead.
type ManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesResponse struct {
    ManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesGetResponse
}
// NewManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesResponse instantiates a new ManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesResponse and sets the default values.
func NewManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesResponse()(*ManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesResponse) {
    m := &ManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesResponse{
        ManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesGetResponse: *NewManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesGetResponse(),
    }
    return m
}
// CreateManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesResponse(), nil
}
// Deprecated: This class is obsolete. Use ManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesGetResponseable instead.
type ManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesResponseable interface {
    ManagedDeviceWindowsOSImagesItemGetAllManagedDeviceWindowsOSImagesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
