package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// MicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponse 
// Deprecated: This class is obsolete. Use generateDownloadUrlPostResponse instead.
type MicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponse struct {
    MicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlPostResponse
}
// NewMicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponse instantiates a new MicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponse and sets the default values.
func NewMicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponse()(*MicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponse) {
    m := &MicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponse{
        MicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlPostResponse: *NewMicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlPostResponse(),
    }
    return m
}
// CreateMicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateMicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponse(), nil
}
// MicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponseable 
// Deprecated: This class is obsolete. Use generateDownloadUrlPostResponse instead.
type MicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlResponseable interface {
    MicrosoftTunnelServerLogCollectionResponsesItemGenerateDownloadUrlPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
