package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use MicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlPostResponseable instead.
type MicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlResponse struct {
    MicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlPostResponse
}
// NewMicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlResponse instantiates a new MicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlResponse and sets the default values.
func NewMicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlResponse()(*MicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlResponse) {
    m := &MicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlResponse{
        MicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlPostResponse: *NewMicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlPostResponse(),
    }
    return m
}
// CreateMicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlResponse(), nil
}
// Deprecated: This class is obsolete. Use MicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlPostResponseable instead.
type MicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlResponseable interface {
    MicrosofttunnelserverlogcollectionresponsesItemGeneratedownloadurlGenerateDownloadUrlPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
