package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// MicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponse 
// Deprecated: This class is obsolete. Use getHealthMetricsPostResponse instead.
type MicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponse struct {
    MicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsPostResponse
}
// NewMicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponse instantiates a new MicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponse and sets the default values.
func NewMicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponse()(*MicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponse) {
    m := &MicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponse{
        MicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsPostResponse: *NewMicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsPostResponse(),
    }
    return m
}
// CreateMicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateMicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponse(), nil
}
// MicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponseable 
// Deprecated: This class is obsolete. Use getHealthMetricsPostResponse instead.
type MicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsResponseable interface {
    MicrosoftTunnelSitesItemMicrosoftTunnelServersItemGetHealthMetricsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
