package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use MicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsPostResponseable instead.
type MicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsResponse struct {
    MicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsPostResponse
}
// NewMicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsResponse instantiates a new MicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsResponse and sets the default values.
func NewMicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsResponse()(*MicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsResponse) {
    m := &MicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsResponse{
        MicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsPostResponse: *NewMicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsPostResponse(),
    }
    return m
}
// CreateMicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsResponse(), nil
}
// Deprecated: This class is obsolete. Use MicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsPostResponseable instead.
type MicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsResponseable interface {
    MicrosofttunnelsitesItemMicrosofttunnelserversItemGethealthmetricsGetHealthMetricsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
