package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use MonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponseable instead.
type MonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse struct {
    MonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponse
}
// NewMonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse instantiates a new MonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse and sets the default values.
func NewMonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse()(*MonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse) {
    m := &MonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse{
        MonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponse: *NewMonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponse(),
    }
    return m
}
// CreateMonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponse(), nil
}
// Deprecated: This class is obsolete. Use MonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponseable instead.
type MonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsResponseable interface {
    MonitoringAlertrecordsMicrosoftgraphdevicemanagementgetportalnotificationsGetPortalNotificationsGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
