package devicemanagement

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i20a3050780ee0b0cde0a884a4f35429a20d60067e3bcda382ec5400079147459 "github.com/microsoftgraph/msgraph-beta-sdk-go/models/odataerrors"
)

// MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder provides operations to call the changeAlertRecordsPortalNotificationAsSent method.
type MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewMonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilderInternal instantiates a new MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder and sets the default values.
func NewMonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder) {
    m := &MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/deviceManagement/monitoring/alertRecords/microsoft.graph.deviceManagement.changeAlertRecordsPortalNotificationAsSent", pathParameters),
    }
    return m
}
// NewMonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder instantiates a new MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder and sets the default values.
func NewMonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewMonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilderInternal(urlParams, requestAdapter)
}
// Post set the isPortalNotificationSent property of all portal notification resources associated with the specified alertRecord to true, marking them as sent. A maximum of 100 alertRecord IDs can be received at one time, and a maximum of 100 portal notification resources can be changed in the isPortalNotificationSent property status.
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder) Post(ctx context.Context, body MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentChangeAlertRecordsPortalNotificationAsSentPostRequestBodyable, requestConfiguration *MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilderPostRequestConfiguration)(error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": i20a3050780ee0b0cde0a884a4f35429a20d60067e3bcda382ec5400079147459.CreateODataErrorFromDiscriminatorValue,
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
    if err != nil {
        return err
    }
    return nil
}
// ToPostRequestInformation set the isPortalNotificationSent property of all portal notification resources associated with the specified alertRecord to true, marking them as sent. A maximum of 100 alertRecord IDs can be received at one time, and a maximum of 100 portal notification resources can be changed in the isPortalNotificationSent property status.
// returns a *RequestInformation when successful
func (m *MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder) ToPostRequestInformation(ctx context.Context, body MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentChangeAlertRecordsPortalNotificationAsSentPostRequestBodyable, requestConfiguration *MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder when successful
func (m *MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder) WithUrl(rawUrl string)(*MonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder) {
    return NewMonitoringAlertrecordsMicrosoftgraphdevicemanagementchangealertrecordsportalnotificationassentMicrosoftGraphDeviceManagementChangeAlertRecordsPortalNotificationAsSentRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
