package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use OperationapprovalrequestsItemCancelapprovalCancelApprovalPostResponseable instead.
type OperationapprovalrequestsItemCancelapprovalCancelApprovalResponse struct {
    OperationapprovalrequestsItemCancelapprovalCancelApprovalPostResponse
}
// NewOperationapprovalrequestsItemCancelapprovalCancelApprovalResponse instantiates a new OperationapprovalrequestsItemCancelapprovalCancelApprovalResponse and sets the default values.
func NewOperationapprovalrequestsItemCancelapprovalCancelApprovalResponse()(*OperationapprovalrequestsItemCancelapprovalCancelApprovalResponse) {
    m := &OperationapprovalrequestsItemCancelapprovalCancelApprovalResponse{
        OperationapprovalrequestsItemCancelapprovalCancelApprovalPostResponse: *NewOperationapprovalrequestsItemCancelapprovalCancelApprovalPostResponse(),
    }
    return m
}
// CreateOperationapprovalrequestsItemCancelapprovalCancelApprovalResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOperationapprovalrequestsItemCancelapprovalCancelApprovalResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewOperationapprovalrequestsItemCancelapprovalCancelApprovalResponse(), nil
}
// Deprecated: This class is obsolete. Use OperationapprovalrequestsItemCancelapprovalCancelApprovalPostResponseable instead.
type OperationapprovalrequestsItemCancelapprovalCancelApprovalResponseable interface {
    OperationapprovalrequestsItemCancelapprovalCancelApprovalPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
