package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use OperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsGetResponseable instead.
type OperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsResponse struct {
    OperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsGetResponse
}
// NewOperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsResponse instantiates a new OperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsResponse and sets the default values.
func NewOperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsResponse()(*OperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsResponse) {
    m := &OperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsResponse{
        OperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsGetResponse: *NewOperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsGetResponse(),
    }
    return m
}
// CreateOperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewOperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsResponse(), nil
}
// Deprecated: This class is obsolete. Use OperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsGetResponseable instead.
type OperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsResponseable interface {
    OperationapprovalrequestsRetrievemyrequestsRetrieveMyRequestsGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
