package devicemanagement

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ie233ee762e29b4ba6970aa2a2efce4b7fde11697ca9ea81099d0f8269309c1be "github.com/microsoftgraph/msgraph-beta-sdk-go/models"
    i20a3050780ee0b0cde0a884a4f35429a20d60067e3bcda382ec5400079147459 "github.com/microsoftgraph/msgraph-beta-sdk-go/models/odataerrors"
)

// ReportsRequestBuilder provides operations to manage the reports property of the microsoft.graph.deviceManagement entity.
type ReportsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ReportsRequestBuilderDeleteRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type ReportsRequestBuilderDeleteRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// ReportsRequestBuilderGetQueryParameters reports singleton
type ReportsRequestBuilderGetQueryParameters struct {
    // Expand related entities
    Expand []string `uriparametername:"%24expand"`
    // Select properties to be returned
    Select []string `uriparametername:"%24select"`
}
// ReportsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type ReportsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *ReportsRequestBuilderGetQueryParameters
}
// ReportsRequestBuilderPatchRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type ReportsRequestBuilderPatchRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// CachedReportConfigurations provides operations to manage the cachedReportConfigurations property of the microsoft.graph.deviceManagementReports entity.
// returns a *ReportsCachedreportconfigurationsCachedReportConfigurationsRequestBuilder when successful
func (m *ReportsRequestBuilder) CachedReportConfigurations()(*ReportsCachedreportconfigurationsCachedReportConfigurationsRequestBuilder) {
    return NewReportsCachedreportconfigurationsCachedReportConfigurationsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewReportsRequestBuilderInternal instantiates a new ReportsRequestBuilder and sets the default values.
func NewReportsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ReportsRequestBuilder) {
    m := &ReportsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/deviceManagement/reports{?%24expand,%24select}", pathParameters),
    }
    return m
}
// NewReportsRequestBuilder instantiates a new ReportsRequestBuilder and sets the default values.
func NewReportsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ReportsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewReportsRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete delete navigation property reports for deviceManagement
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *ReportsRequestBuilder) Delete(ctx context.Context, requestConfiguration *ReportsRequestBuilderDeleteRequestConfiguration)(error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": i20a3050780ee0b0cde0a884a4f35429a20d60067e3bcda382ec5400079147459.CreateODataErrorFromDiscriminatorValue,
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
    if err != nil {
        return err
    }
    return nil
}
// ExportJobs provides operations to manage the exportJobs property of the microsoft.graph.deviceManagementReports entity.
// returns a *ReportsExportjobsExportJobsRequestBuilder when successful
func (m *ReportsRequestBuilder) ExportJobs()(*ReportsExportjobsExportJobsRequestBuilder) {
    return NewReportsExportjobsExportJobsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Get reports singleton
// returns a DeviceManagementReportsable when successful
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *ReportsRequestBuilder) Get(ctx context.Context, requestConfiguration *ReportsRequestBuilderGetRequestConfiguration)(ie233ee762e29b4ba6970aa2a2efce4b7fde11697ca9ea81099d0f8269309c1be.DeviceManagementReportsable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": i20a3050780ee0b0cde0a884a4f35429a20d60067e3bcda382ec5400079147459.CreateODataErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ie233ee762e29b4ba6970aa2a2efce4b7fde11697ca9ea81099d0f8269309c1be.CreateDeviceManagementReportsFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ie233ee762e29b4ba6970aa2a2efce4b7fde11697ca9ea81099d0f8269309c1be.DeviceManagementReportsable), nil
}
// GetActiveMalwareReport provides operations to call the getActiveMalwareReport method.
// returns a *ReportsGetactivemalwarereportGetActiveMalwareReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetActiveMalwareReport()(*ReportsGetactivemalwarereportGetActiveMalwareReportRequestBuilder) {
    return NewReportsGetactivemalwarereportGetActiveMalwareReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetActiveMalwareSummaryReport provides operations to call the getActiveMalwareSummaryReport method.
// returns a *ReportsGetactivemalwaresummaryreportGetActiveMalwareSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetActiveMalwareSummaryReport()(*ReportsGetactivemalwaresummaryreportGetActiveMalwareSummaryReportRequestBuilder) {
    return NewReportsGetactivemalwaresummaryreportGetActiveMalwareSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetAllCertificatesReport provides operations to call the getAllCertificatesReport method.
// returns a *ReportsGetallcertificatesreportGetAllCertificatesReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetAllCertificatesReport()(*ReportsGetallcertificatesreportGetAllCertificatesReportRequestBuilder) {
    return NewReportsGetallcertificatesreportGetAllCertificatesReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetAppsInstallSummaryReport provides operations to call the getAppsInstallSummaryReport method.
// returns a *ReportsGetappsinstallsummaryreportGetAppsInstallSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetAppsInstallSummaryReport()(*ReportsGetappsinstallsummaryreportGetAppsInstallSummaryReportRequestBuilder) {
    return NewReportsGetappsinstallsummaryreportGetAppsInstallSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetAppStatusOverviewReport provides operations to call the getAppStatusOverviewReport method.
// returns a *ReportsGetappstatusoverviewreportGetAppStatusOverviewReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetAppStatusOverviewReport()(*ReportsGetappstatusoverviewreportGetAppStatusOverviewReportRequestBuilder) {
    return NewReportsGetappstatusoverviewreportGetAppStatusOverviewReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetCachedReport provides operations to call the getCachedReport method.
// returns a *ReportsGetcachedreportGetCachedReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetCachedReport()(*ReportsGetcachedreportGetCachedReportRequestBuilder) {
    return NewReportsGetcachedreportGetCachedReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetCertificatesReport provides operations to call the getCertificatesReport method.
// returns a *ReportsGetcertificatesreportGetCertificatesReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetCertificatesReport()(*ReportsGetcertificatesreportGetCertificatesReportRequestBuilder) {
    return NewReportsGetcertificatesreportGetCertificatesReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetCompliancePoliciesReportForDevice provides operations to call the getCompliancePoliciesReportForDevice method.
// returns a *ReportsGetcompliancepoliciesreportfordeviceGetCompliancePoliciesReportForDeviceRequestBuilder when successful
func (m *ReportsRequestBuilder) GetCompliancePoliciesReportForDevice()(*ReportsGetcompliancepoliciesreportfordeviceGetCompliancePoliciesReportForDeviceRequestBuilder) {
    return NewReportsGetcompliancepoliciesreportfordeviceGetCompliancePoliciesReportForDeviceRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetCompliancePolicyDevicesReport provides operations to call the getCompliancePolicyDevicesReport method.
// returns a *ReportsGetcompliancepolicydevicesreportGetCompliancePolicyDevicesReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetCompliancePolicyDevicesReport()(*ReportsGetcompliancepolicydevicesreportGetCompliancePolicyDevicesReportRequestBuilder) {
    return NewReportsGetcompliancepolicydevicesreportGetCompliancePolicyDevicesReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetCompliancePolicyDeviceSummaryReport provides operations to call the getCompliancePolicyDeviceSummaryReport method.
// returns a *ReportsGetcompliancepolicydevicesummaryreportGetCompliancePolicyDeviceSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetCompliancePolicyDeviceSummaryReport()(*ReportsGetcompliancepolicydevicesummaryreportGetCompliancePolicyDeviceSummaryReportRequestBuilder) {
    return NewReportsGetcompliancepolicydevicesummaryreportGetCompliancePolicyDeviceSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetCompliancePolicyNonComplianceReport provides operations to call the getCompliancePolicyNonComplianceReport method.
// returns a *ReportsGetcompliancepolicynoncompliancereportGetCompliancePolicyNonComplianceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetCompliancePolicyNonComplianceReport()(*ReportsGetcompliancepolicynoncompliancereportGetCompliancePolicyNonComplianceReportRequestBuilder) {
    return NewReportsGetcompliancepolicynoncompliancereportGetCompliancePolicyNonComplianceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetCompliancePolicyNonComplianceSummaryReport provides operations to call the getCompliancePolicyNonComplianceSummaryReport method.
// returns a *ReportsGetcompliancepolicynoncompliancesummaryreportGetCompliancePolicyNonComplianceSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetCompliancePolicyNonComplianceSummaryReport()(*ReportsGetcompliancepolicynoncompliancesummaryreportGetCompliancePolicyNonComplianceSummaryReportRequestBuilder) {
    return NewReportsGetcompliancepolicynoncompliancesummaryreportGetCompliancePolicyNonComplianceSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetComplianceSettingDetailsReport provides operations to call the getComplianceSettingDetailsReport method.
// returns a *ReportsGetcompliancesettingdetailsreportGetComplianceSettingDetailsReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetComplianceSettingDetailsReport()(*ReportsGetcompliancesettingdetailsreportGetComplianceSettingDetailsReportRequestBuilder) {
    return NewReportsGetcompliancesettingdetailsreportGetComplianceSettingDetailsReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetComplianceSettingNonComplianceReport provides operations to call the getComplianceSettingNonComplianceReport method.
// returns a *ReportsGetcompliancesettingnoncompliancereportGetComplianceSettingNonComplianceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetComplianceSettingNonComplianceReport()(*ReportsGetcompliancesettingnoncompliancereportGetComplianceSettingNonComplianceReportRequestBuilder) {
    return NewReportsGetcompliancesettingnoncompliancereportGetComplianceSettingNonComplianceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetComplianceSettingsReport provides operations to call the getComplianceSettingsReport method.
// returns a *ReportsGetcompliancesettingsreportGetComplianceSettingsReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetComplianceSettingsReport()(*ReportsGetcompliancesettingsreportGetComplianceSettingsReportRequestBuilder) {
    return NewReportsGetcompliancesettingsreportGetComplianceSettingsReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetConfigManagerDevicePolicyStatusReport provides operations to call the getConfigManagerDevicePolicyStatusReport method.
// returns a *ReportsGetconfigmanagerdevicepolicystatusreportGetConfigManagerDevicePolicyStatusReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetConfigManagerDevicePolicyStatusReport()(*ReportsGetconfigmanagerdevicepolicystatusreportGetConfigManagerDevicePolicyStatusReportRequestBuilder) {
    return NewReportsGetconfigmanagerdevicepolicystatusreportGetConfigManagerDevicePolicyStatusReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetConfigurationPoliciesReportForDevice provides operations to call the getConfigurationPoliciesReportForDevice method.
// returns a *ReportsGetconfigurationpoliciesreportfordeviceGetConfigurationPoliciesReportForDeviceRequestBuilder when successful
func (m *ReportsRequestBuilder) GetConfigurationPoliciesReportForDevice()(*ReportsGetconfigurationpoliciesreportfordeviceGetConfigurationPoliciesReportForDeviceRequestBuilder) {
    return NewReportsGetconfigurationpoliciesreportfordeviceGetConfigurationPoliciesReportForDeviceRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetConfigurationPolicyDevicesReport provides operations to call the getConfigurationPolicyDevicesReport method.
// returns a *ReportsGetconfigurationpolicydevicesreportGetConfigurationPolicyDevicesReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetConfigurationPolicyDevicesReport()(*ReportsGetconfigurationpolicydevicesreportGetConfigurationPolicyDevicesReportRequestBuilder) {
    return NewReportsGetconfigurationpolicydevicesreportGetConfigurationPolicyDevicesReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetConfigurationPolicyDeviceSummaryReport provides operations to call the getConfigurationPolicyDeviceSummaryReport method.
// returns a *ReportsGetconfigurationpolicydevicesummaryreportGetConfigurationPolicyDeviceSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetConfigurationPolicyDeviceSummaryReport()(*ReportsGetconfigurationpolicydevicesummaryreportGetConfigurationPolicyDeviceSummaryReportRequestBuilder) {
    return NewReportsGetconfigurationpolicydevicesummaryreportGetConfigurationPolicyDeviceSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetConfigurationPolicyNonComplianceReport provides operations to call the getConfigurationPolicyNonComplianceReport method.
// returns a *ReportsGetconfigurationpolicynoncompliancereportGetConfigurationPolicyNonComplianceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetConfigurationPolicyNonComplianceReport()(*ReportsGetconfigurationpolicynoncompliancereportGetConfigurationPolicyNonComplianceReportRequestBuilder) {
    return NewReportsGetconfigurationpolicynoncompliancereportGetConfigurationPolicyNonComplianceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetConfigurationPolicyNonComplianceSummaryReport provides operations to call the getConfigurationPolicyNonComplianceSummaryReport method.
// returns a *ReportsGetconfigurationpolicynoncompliancesummaryreportGetConfigurationPolicyNonComplianceSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetConfigurationPolicyNonComplianceSummaryReport()(*ReportsGetconfigurationpolicynoncompliancesummaryreportGetConfigurationPolicyNonComplianceSummaryReportRequestBuilder) {
    return NewReportsGetconfigurationpolicynoncompliancesummaryreportGetConfigurationPolicyNonComplianceSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetConfigurationPolicySettingsDeviceSummaryReport provides operations to call the getConfigurationPolicySettingsDeviceSummaryReport method.
// returns a *ReportsGetconfigurationpolicysettingsdevicesummaryreportGetConfigurationPolicySettingsDeviceSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetConfigurationPolicySettingsDeviceSummaryReport()(*ReportsGetconfigurationpolicysettingsdevicesummaryreportGetConfigurationPolicySettingsDeviceSummaryReportRequestBuilder) {
    return NewReportsGetconfigurationpolicysettingsdevicesummaryreportGetConfigurationPolicySettingsDeviceSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetConfigurationSettingDetailsReport provides operations to call the getConfigurationSettingDetailsReport method.
// returns a *ReportsGetconfigurationsettingdetailsreportGetConfigurationSettingDetailsReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetConfigurationSettingDetailsReport()(*ReportsGetconfigurationsettingdetailsreportGetConfigurationSettingDetailsReportRequestBuilder) {
    return NewReportsGetconfigurationsettingdetailsreportGetConfigurationSettingDetailsReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetConfigurationSettingNonComplianceReport provides operations to call the getConfigurationSettingNonComplianceReport method.
// returns a *ReportsGetconfigurationsettingnoncompliancereportGetConfigurationSettingNonComplianceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetConfigurationSettingNonComplianceReport()(*ReportsGetconfigurationsettingnoncompliancereportGetConfigurationSettingNonComplianceReportRequestBuilder) {
    return NewReportsGetconfigurationsettingnoncompliancereportGetConfigurationSettingNonComplianceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetConfigurationSettingsReport provides operations to call the getConfigurationSettingsReport method.
// returns a *ReportsGetconfigurationsettingsreportGetConfigurationSettingsReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetConfigurationSettingsReport()(*ReportsGetconfigurationsettingsreportGetConfigurationSettingsReportRequestBuilder) {
    return NewReportsGetconfigurationsettingsreportGetConfigurationSettingsReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDeviceConfigurationPolicySettingsSummaryReport provides operations to call the getDeviceConfigurationPolicySettingsSummaryReport method.
// returns a *ReportsGetdeviceconfigurationpolicysettingssummaryreportGetDeviceConfigurationPolicySettingsSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDeviceConfigurationPolicySettingsSummaryReport()(*ReportsGetdeviceconfigurationpolicysettingssummaryreportGetDeviceConfigurationPolicySettingsSummaryReportRequestBuilder) {
    return NewReportsGetdeviceconfigurationpolicysettingssummaryreportGetDeviceConfigurationPolicySettingsSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDeviceConfigurationPolicyStatusSummary provides operations to call the getDeviceConfigurationPolicyStatusSummary method.
// returns a *ReportsGetdeviceconfigurationpolicystatussummaryGetDeviceConfigurationPolicyStatusSummaryRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDeviceConfigurationPolicyStatusSummary()(*ReportsGetdeviceconfigurationpolicystatussummaryGetDeviceConfigurationPolicyStatusSummaryRequestBuilder) {
    return NewReportsGetdeviceconfigurationpolicystatussummaryGetDeviceConfigurationPolicyStatusSummaryRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDeviceInstallStatusReport provides operations to call the getDeviceInstallStatusReport method.
// returns a *ReportsGetdeviceinstallstatusreportGetDeviceInstallStatusReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDeviceInstallStatusReport()(*ReportsGetdeviceinstallstatusreportGetDeviceInstallStatusReportRequestBuilder) {
    return NewReportsGetdeviceinstallstatusreportGetDeviceInstallStatusReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDeviceManagementIntentPerSettingContributingProfiles provides operations to call the getDeviceManagementIntentPerSettingContributingProfiles method.
// returns a *ReportsGetdevicemanagementintentpersettingcontributingprofilesGetDeviceManagementIntentPerSettingContributingProfilesRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDeviceManagementIntentPerSettingContributingProfiles()(*ReportsGetdevicemanagementintentpersettingcontributingprofilesGetDeviceManagementIntentPerSettingContributingProfilesRequestBuilder) {
    return NewReportsGetdevicemanagementintentpersettingcontributingprofilesGetDeviceManagementIntentPerSettingContributingProfilesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDeviceManagementIntentSettingsReport provides operations to call the getDeviceManagementIntentSettingsReport method.
// returns a *ReportsGetdevicemanagementintentsettingsreportGetDeviceManagementIntentSettingsReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDeviceManagementIntentSettingsReport()(*ReportsGetdevicemanagementintentsettingsreportGetDeviceManagementIntentSettingsReportRequestBuilder) {
    return NewReportsGetdevicemanagementintentsettingsreportGetDeviceManagementIntentSettingsReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDeviceNonComplianceReport provides operations to call the getDeviceNonComplianceReport method.
// returns a *ReportsGetdevicenoncompliancereportGetDeviceNonComplianceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDeviceNonComplianceReport()(*ReportsGetdevicenoncompliancereportGetDeviceNonComplianceReportRequestBuilder) {
    return NewReportsGetdevicenoncompliancereportGetDeviceNonComplianceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDevicePoliciesComplianceReport provides operations to call the getDevicePoliciesComplianceReport method.
// returns a *ReportsGetdevicepoliciescompliancereportGetDevicePoliciesComplianceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDevicePoliciesComplianceReport()(*ReportsGetdevicepoliciescompliancereportGetDevicePoliciesComplianceReportRequestBuilder) {
    return NewReportsGetdevicepoliciescompliancereportGetDevicePoliciesComplianceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDevicePolicySettingsComplianceReport provides operations to call the getDevicePolicySettingsComplianceReport method.
// returns a *ReportsGetdevicepolicysettingscompliancereportGetDevicePolicySettingsComplianceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDevicePolicySettingsComplianceReport()(*ReportsGetdevicepolicysettingscompliancereportGetDevicePolicySettingsComplianceReportRequestBuilder) {
    return NewReportsGetdevicepolicysettingscompliancereportGetDevicePolicySettingsComplianceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDevicesStatusByPolicyPlatformComplianceReport provides operations to call the getDevicesStatusByPolicyPlatformComplianceReport method.
// returns a *ReportsGetdevicesstatusbypolicyplatformcompliancereportGetDevicesStatusByPolicyPlatformComplianceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDevicesStatusByPolicyPlatformComplianceReport()(*ReportsGetdevicesstatusbypolicyplatformcompliancereportGetDevicesStatusByPolicyPlatformComplianceReportRequestBuilder) {
    return NewReportsGetdevicesstatusbypolicyplatformcompliancereportGetDevicesStatusByPolicyPlatformComplianceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDevicesStatusBySettingReport provides operations to call the getDevicesStatusBySettingReport method.
// returns a *ReportsGetdevicesstatusbysettingreportGetDevicesStatusBySettingReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDevicesStatusBySettingReport()(*ReportsGetdevicesstatusbysettingreportGetDevicesStatusBySettingReportRequestBuilder) {
    return NewReportsGetdevicesstatusbysettingreportGetDevicesStatusBySettingReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDeviceStatusByCompliacePolicyReport provides operations to call the getDeviceStatusByCompliacePolicyReport method.
// returns a *ReportsGetdevicestatusbycompliacepolicyreportGetDeviceStatusByCompliacePolicyReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDeviceStatusByCompliacePolicyReport()(*ReportsGetdevicestatusbycompliacepolicyreportGetDeviceStatusByCompliacePolicyReportRequestBuilder) {
    return NewReportsGetdevicestatusbycompliacepolicyreportGetDeviceStatusByCompliacePolicyReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDeviceStatusByCompliancePolicySettingReport provides operations to call the getDeviceStatusByCompliancePolicySettingReport method.
// returns a *ReportsGetdevicestatusbycompliancepolicysettingreportGetDeviceStatusByCompliancePolicySettingReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDeviceStatusByCompliancePolicySettingReport()(*ReportsGetdevicestatusbycompliancepolicysettingreportGetDeviceStatusByCompliancePolicySettingReportRequestBuilder) {
    return NewReportsGetdevicestatusbycompliancepolicysettingreportGetDeviceStatusByCompliancePolicySettingReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDeviceStatusSummaryByCompliacePolicyReport provides operations to call the getDeviceStatusSummaryByCompliacePolicyReport method.
// returns a *ReportsGetdevicestatussummarybycompliacepolicyreportGetDeviceStatusSummaryByCompliacePolicyReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDeviceStatusSummaryByCompliacePolicyReport()(*ReportsGetdevicestatussummarybycompliacepolicyreportGetDeviceStatusSummaryByCompliacePolicyReportRequestBuilder) {
    return NewReportsGetdevicestatussummarybycompliacepolicyreportGetDeviceStatusSummaryByCompliacePolicyReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDeviceStatusSummaryByCompliancePolicySettingsReport provides operations to call the getDeviceStatusSummaryByCompliancePolicySettingsReport method.
// returns a *ReportsGetdevicestatussummarybycompliancepolicysettingsreportGetDeviceStatusSummaryByCompliancePolicySettingsReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDeviceStatusSummaryByCompliancePolicySettingsReport()(*ReportsGetdevicestatussummarybycompliancepolicysettingsreportGetDeviceStatusSummaryByCompliancePolicySettingsReportRequestBuilder) {
    return NewReportsGetdevicestatussummarybycompliancepolicysettingsreportGetDeviceStatusSummaryByCompliancePolicySettingsReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetDevicesWithoutCompliancePolicyReport provides operations to call the getDevicesWithoutCompliancePolicyReport method.
// returns a *ReportsGetdeviceswithoutcompliancepolicyreportGetDevicesWithoutCompliancePolicyReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetDevicesWithoutCompliancePolicyReport()(*ReportsGetdeviceswithoutcompliancepolicyreportGetDevicesWithoutCompliancePolicyReportRequestBuilder) {
    return NewReportsGetdeviceswithoutcompliancepolicyreportGetDevicesWithoutCompliancePolicyReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetEncryptionReportForDevices provides operations to call the getEncryptionReportForDevices method.
// returns a *ReportsGetencryptionreportfordevicesGetEncryptionReportForDevicesRequestBuilder when successful
func (m *ReportsRequestBuilder) GetEncryptionReportForDevices()(*ReportsGetencryptionreportfordevicesGetEncryptionReportForDevicesRequestBuilder) {
    return NewReportsGetencryptionreportfordevicesGetEncryptionReportForDevicesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetEnrollmentConfigurationPoliciesByDevice provides operations to call the getEnrollmentConfigurationPoliciesByDevice method.
// returns a *ReportsGetenrollmentconfigurationpoliciesbydeviceGetEnrollmentConfigurationPoliciesByDeviceRequestBuilder when successful
func (m *ReportsRequestBuilder) GetEnrollmentConfigurationPoliciesByDevice()(*ReportsGetenrollmentconfigurationpoliciesbydeviceGetEnrollmentConfigurationPoliciesByDeviceRequestBuilder) {
    return NewReportsGetenrollmentconfigurationpoliciesbydeviceGetEnrollmentConfigurationPoliciesByDeviceRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetFailedMobileAppsReport provides operations to call the getFailedMobileAppsReport method.
// returns a *ReportsGetfailedmobileappsreportGetFailedMobileAppsReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetFailedMobileAppsReport()(*ReportsGetfailedmobileappsreportGetFailedMobileAppsReportRequestBuilder) {
    return NewReportsGetfailedmobileappsreportGetFailedMobileAppsReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetFailedMobileAppsSummaryReport provides operations to call the getFailedMobileAppsSummaryReport method.
// returns a *ReportsGetfailedmobileappssummaryreportGetFailedMobileAppsSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetFailedMobileAppsSummaryReport()(*ReportsGetfailedmobileappssummaryreportGetFailedMobileAppsSummaryReportRequestBuilder) {
    return NewReportsGetfailedmobileappssummaryreportGetFailedMobileAppsSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetGroupPolicySettingsDeviceSettingsReport provides operations to call the getGroupPolicySettingsDeviceSettingsReport method.
// returns a *ReportsGetgrouppolicysettingsdevicesettingsreportGetGroupPolicySettingsDeviceSettingsReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetGroupPolicySettingsDeviceSettingsReport()(*ReportsGetgrouppolicysettingsdevicesettingsreportGetGroupPolicySettingsDeviceSettingsReportRequestBuilder) {
    return NewReportsGetgrouppolicysettingsdevicesettingsreportGetGroupPolicySettingsDeviceSettingsReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetHistoricalReport provides operations to call the getHistoricalReport method.
// returns a *ReportsGethistoricalreportGetHistoricalReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetHistoricalReport()(*ReportsGethistoricalreportGetHistoricalReportRequestBuilder) {
    return NewReportsGethistoricalreportGetHistoricalReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetMalwareSummaryReport provides operations to call the getMalwareSummaryReport method.
// returns a *ReportsGetmalwaresummaryreportGetMalwareSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetMalwareSummaryReport()(*ReportsGetmalwaresummaryreportGetMalwareSummaryReportRequestBuilder) {
    return NewReportsGetmalwaresummaryreportGetMalwareSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetMobileApplicationManagementAppConfigurationReport provides operations to call the getMobileApplicationManagementAppConfigurationReport method.
// returns a *ReportsGetmobileapplicationmanagementappconfigurationreportGetMobileApplicationManagementAppConfigurationReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetMobileApplicationManagementAppConfigurationReport()(*ReportsGetmobileapplicationmanagementappconfigurationreportGetMobileApplicationManagementAppConfigurationReportRequestBuilder) {
    return NewReportsGetmobileapplicationmanagementappconfigurationreportGetMobileApplicationManagementAppConfigurationReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetMobileApplicationManagementAppRegistrationSummaryReport provides operations to call the getMobileApplicationManagementAppRegistrationSummaryReport method.
// returns a *ReportsGetmobileapplicationmanagementappregistrationsummaryreportGetMobileApplicationManagementAppRegistrationSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetMobileApplicationManagementAppRegistrationSummaryReport()(*ReportsGetmobileapplicationmanagementappregistrationsummaryreportGetMobileApplicationManagementAppRegistrationSummaryReportRequestBuilder) {
    return NewReportsGetmobileapplicationmanagementappregistrationsummaryreportGetMobileApplicationManagementAppRegistrationSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetNoncompliantDevicesAndSettingsReport provides operations to call the getNoncompliantDevicesAndSettingsReport method.
// returns a *ReportsGetnoncompliantdevicesandsettingsreportGetNoncompliantDevicesAndSettingsReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetNoncompliantDevicesAndSettingsReport()(*ReportsGetnoncompliantdevicesandsettingsreportGetNoncompliantDevicesAndSettingsReportRequestBuilder) {
    return NewReportsGetnoncompliantdevicesandsettingsreportGetNoncompliantDevicesAndSettingsReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetPolicyNonComplianceMetadata provides operations to call the getPolicyNonComplianceMetadata method.
// returns a *ReportsGetpolicynoncompliancemetadataGetPolicyNonComplianceMetadataRequestBuilder when successful
func (m *ReportsRequestBuilder) GetPolicyNonComplianceMetadata()(*ReportsGetpolicynoncompliancemetadataGetPolicyNonComplianceMetadataRequestBuilder) {
    return NewReportsGetpolicynoncompliancemetadataGetPolicyNonComplianceMetadataRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetPolicyNonComplianceReport provides operations to call the getPolicyNonComplianceReport method.
// returns a *ReportsGetpolicynoncompliancereportGetPolicyNonComplianceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetPolicyNonComplianceReport()(*ReportsGetpolicynoncompliancereportGetPolicyNonComplianceReportRequestBuilder) {
    return NewReportsGetpolicynoncompliancereportGetPolicyNonComplianceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetPolicyNonComplianceSummaryReport provides operations to call the getPolicyNonComplianceSummaryReport method.
// returns a *ReportsGetpolicynoncompliancesummaryreportGetPolicyNonComplianceSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetPolicyNonComplianceSummaryReport()(*ReportsGetpolicynoncompliancesummaryreportGetPolicyNonComplianceSummaryReportRequestBuilder) {
    return NewReportsGetpolicynoncompliancesummaryreportGetPolicyNonComplianceSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetQuietTimePolicyUsersReport provides operations to call the getQuietTimePolicyUsersReport method.
// returns a *ReportsGetquiettimepolicyusersreportGetQuietTimePolicyUsersReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetQuietTimePolicyUsersReport()(*ReportsGetquiettimepolicyusersreportGetQuietTimePolicyUsersReportRequestBuilder) {
    return NewReportsGetquiettimepolicyusersreportGetQuietTimePolicyUsersReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetQuietTimePolicyUserSummaryReport provides operations to call the getQuietTimePolicyUserSummaryReport method.
// returns a *ReportsGetquiettimepolicyusersummaryreportGetQuietTimePolicyUserSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetQuietTimePolicyUserSummaryReport()(*ReportsGetquiettimepolicyusersummaryreportGetQuietTimePolicyUserSummaryReportRequestBuilder) {
    return NewReportsGetquiettimepolicyusersummaryreportGetQuietTimePolicyUserSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetRelatedAppsStatusReport provides operations to call the getRelatedAppsStatusReport method.
// returns a *ReportsGetrelatedappsstatusreportGetRelatedAppsStatusReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetRelatedAppsStatusReport()(*ReportsGetrelatedappsstatusreportGetRelatedAppsStatusReportRequestBuilder) {
    return NewReportsGetrelatedappsstatusreportGetRelatedAppsStatusReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetRemoteAssistanceSessionsReport provides operations to call the getRemoteAssistanceSessionsReport method.
// returns a *ReportsGetremoteassistancesessionsreportGetRemoteAssistanceSessionsReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetRemoteAssistanceSessionsReport()(*ReportsGetremoteassistancesessionsreportGetRemoteAssistanceSessionsReportRequestBuilder) {
    return NewReportsGetremoteassistancesessionsreportGetRemoteAssistanceSessionsReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetReportFilters provides operations to call the getReportFilters method.
// returns a *ReportsGetreportfiltersGetReportFiltersRequestBuilder when successful
func (m *ReportsRequestBuilder) GetReportFilters()(*ReportsGetreportfiltersGetReportFiltersRequestBuilder) {
    return NewReportsGetreportfiltersGetReportFiltersRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetSettingNonComplianceReport provides operations to call the getSettingNonComplianceReport method.
// returns a *ReportsGetsettingnoncompliancereportGetSettingNonComplianceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetSettingNonComplianceReport()(*ReportsGetsettingnoncompliancereportGetSettingNonComplianceReportRequestBuilder) {
    return NewReportsGetsettingnoncompliancereportGetSettingNonComplianceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetUnhealthyDefenderAgentsReport provides operations to call the getUnhealthyDefenderAgentsReport method.
// returns a *ReportsGetunhealthydefenderagentsreportGetUnhealthyDefenderAgentsReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetUnhealthyDefenderAgentsReport()(*ReportsGetunhealthydefenderagentsreportGetUnhealthyDefenderAgentsReportRequestBuilder) {
    return NewReportsGetunhealthydefenderagentsreportGetUnhealthyDefenderAgentsReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetUnhealthyFirewallReport provides operations to call the getUnhealthyFirewallReport method.
// returns a *ReportsGetunhealthyfirewallreportGetUnhealthyFirewallReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetUnhealthyFirewallReport()(*ReportsGetunhealthyfirewallreportGetUnhealthyFirewallReportRequestBuilder) {
    return NewReportsGetunhealthyfirewallreportGetUnhealthyFirewallReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetUnhealthyFirewallSummaryReport provides operations to call the getUnhealthyFirewallSummaryReport method.
// returns a *ReportsGetunhealthyfirewallsummaryreportGetUnhealthyFirewallSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetUnhealthyFirewallSummaryReport()(*ReportsGetunhealthyfirewallsummaryreportGetUnhealthyFirewallSummaryReportRequestBuilder) {
    return NewReportsGetunhealthyfirewallsummaryreportGetUnhealthyFirewallSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetUserInstallStatusReport provides operations to call the getUserInstallStatusReport method.
// returns a *ReportsGetuserinstallstatusreportGetUserInstallStatusReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetUserInstallStatusReport()(*ReportsGetuserinstallstatusreportGetUserInstallStatusReportRequestBuilder) {
    return NewReportsGetuserinstallstatusreportGetUserInstallStatusReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetWindowsDriverUpdateAlertsPerPolicyPerDeviceReport provides operations to call the getWindowsDriverUpdateAlertsPerPolicyPerDeviceReport method.
// returns a *ReportsGetwindowsdriverupdatealertsperpolicyperdevicereportGetWindowsDriverUpdateAlertsPerPolicyPerDeviceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetWindowsDriverUpdateAlertsPerPolicyPerDeviceReport()(*ReportsGetwindowsdriverupdatealertsperpolicyperdevicereportGetWindowsDriverUpdateAlertsPerPolicyPerDeviceReportRequestBuilder) {
    return NewReportsGetwindowsdriverupdatealertsperpolicyperdevicereportGetWindowsDriverUpdateAlertsPerPolicyPerDeviceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetWindowsDriverUpdateAlertSummaryReport provides operations to call the getWindowsDriverUpdateAlertSummaryReport method.
// returns a *ReportsGetwindowsdriverupdatealertsummaryreportGetWindowsDriverUpdateAlertSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetWindowsDriverUpdateAlertSummaryReport()(*ReportsGetwindowsdriverupdatealertsummaryreportGetWindowsDriverUpdateAlertSummaryReportRequestBuilder) {
    return NewReportsGetwindowsdriverupdatealertsummaryreportGetWindowsDriverUpdateAlertSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetWindowsQualityUpdateAlertsPerPolicyPerDeviceReport provides operations to call the getWindowsQualityUpdateAlertsPerPolicyPerDeviceReport method.
// returns a *ReportsGetwindowsqualityupdatealertsperpolicyperdevicereportGetWindowsQualityUpdateAlertsPerPolicyPerDeviceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetWindowsQualityUpdateAlertsPerPolicyPerDeviceReport()(*ReportsGetwindowsqualityupdatealertsperpolicyperdevicereportGetWindowsQualityUpdateAlertsPerPolicyPerDeviceReportRequestBuilder) {
    return NewReportsGetwindowsqualityupdatealertsperpolicyperdevicereportGetWindowsQualityUpdateAlertsPerPolicyPerDeviceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetWindowsQualityUpdateAlertSummaryReport provides operations to call the getWindowsQualityUpdateAlertSummaryReport method.
// returns a *ReportsGetwindowsqualityupdatealertsummaryreportGetWindowsQualityUpdateAlertSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetWindowsQualityUpdateAlertSummaryReport()(*ReportsGetwindowsqualityupdatealertsummaryreportGetWindowsQualityUpdateAlertSummaryReportRequestBuilder) {
    return NewReportsGetwindowsqualityupdatealertsummaryreportGetWindowsQualityUpdateAlertSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetWindowsUpdateAlertsPerPolicyPerDeviceReport provides operations to call the getWindowsUpdateAlertsPerPolicyPerDeviceReport method.
// returns a *ReportsGetwindowsupdatealertsperpolicyperdevicereportGetWindowsUpdateAlertsPerPolicyPerDeviceReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetWindowsUpdateAlertsPerPolicyPerDeviceReport()(*ReportsGetwindowsupdatealertsperpolicyperdevicereportGetWindowsUpdateAlertsPerPolicyPerDeviceReportRequestBuilder) {
    return NewReportsGetwindowsupdatealertsperpolicyperdevicereportGetWindowsUpdateAlertsPerPolicyPerDeviceReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetWindowsUpdateAlertSummaryReport provides operations to call the getWindowsUpdateAlertSummaryReport method.
// returns a *ReportsGetwindowsupdatealertsummaryreportGetWindowsUpdateAlertSummaryReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetWindowsUpdateAlertSummaryReport()(*ReportsGetwindowsupdatealertsummaryreportGetWindowsUpdateAlertSummaryReportRequestBuilder) {
    return NewReportsGetwindowsupdatealertsummaryreportGetWindowsUpdateAlertSummaryReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// GetZebraFotaDeploymentReport provides operations to call the getZebraFotaDeploymentReport method.
// returns a *ReportsGetzebrafotadeploymentreportGetZebraFotaDeploymentReportRequestBuilder when successful
func (m *ReportsRequestBuilder) GetZebraFotaDeploymentReport()(*ReportsGetzebrafotadeploymentreportGetZebraFotaDeploymentReportRequestBuilder) {
    return NewReportsGetzebrafotadeploymentreportGetZebraFotaDeploymentReportRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Patch update the navigation property reports in deviceManagement
// returns a DeviceManagementReportsable when successful
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *ReportsRequestBuilder) Patch(ctx context.Context, body ie233ee762e29b4ba6970aa2a2efce4b7fde11697ca9ea81099d0f8269309c1be.DeviceManagementReportsable, requestConfiguration *ReportsRequestBuilderPatchRequestConfiguration)(ie233ee762e29b4ba6970aa2a2efce4b7fde11697ca9ea81099d0f8269309c1be.DeviceManagementReportsable, error) {
    requestInfo, err := m.ToPatchRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": i20a3050780ee0b0cde0a884a4f35429a20d60067e3bcda382ec5400079147459.CreateODataErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ie233ee762e29b4ba6970aa2a2efce4b7fde11697ca9ea81099d0f8269309c1be.CreateDeviceManagementReportsFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ie233ee762e29b4ba6970aa2a2efce4b7fde11697ca9ea81099d0f8269309c1be.DeviceManagementReportsable), nil
}
// ToDeleteRequestInformation delete navigation property reports for deviceManagement
// returns a *RequestInformation when successful
func (m *ReportsRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *ReportsRequestBuilderDeleteRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToGetRequestInformation reports singleton
// returns a *RequestInformation when successful
func (m *ReportsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *ReportsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToPatchRequestInformation update the navigation property reports in deviceManagement
// returns a *RequestInformation when successful
func (m *ReportsRequestBuilder) ToPatchRequestInformation(ctx context.Context, body ie233ee762e29b4ba6970aa2a2efce4b7fde11697ca9ea81099d0f8269309c1be.DeviceManagementReportsable, requestConfiguration *ReportsRequestBuilderPatchRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.PATCH, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ReportsRequestBuilder when successful
func (m *ReportsRequestBuilder) WithUrl(rawUrl string)(*ReportsRequestBuilder) {
    return NewReportsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
