package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponseable instead.
type ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse struct {
    ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponse
}
// NewReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse instantiates a new ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse and sets the default values.
func NewReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse()(*ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse) {
    m := &ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse{
        ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponse: *NewReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponse(),
    }
    return m
}
// CreateReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponse(), nil
}
// Deprecated: This class is obsolete. Use ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponseable instead.
type ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignjustintimeconfigurationAssignJustInTimeConfigurationPostResponseable
}
