package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignPostResponseable instead.
type ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignResponse struct {
    ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignPostResponse
}
// NewReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignResponse instantiates a new ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignResponse and sets the default values.
func NewReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignResponse()(*ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignResponse) {
    m := &ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignResponse{
        ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignPostResponse: *NewReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignPostResponse(),
    }
    return m
}
// CreateReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignResponse(), nil
}
// Deprecated: This class is obsolete. Use ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignPostResponseable instead.
type ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    ReusablepolicysettingsItemReferencingconfigurationpoliciesItemAssignPostResponseable
}
