package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ScopedforresourcewithresourceScopedForResourceWithResourceGetResponseable instead.
type ScopedforresourcewithresourceScopedForResourceWithResourceResponse struct {
    ScopedforresourcewithresourceScopedForResourceWithResourceGetResponse
}
// NewScopedforresourcewithresourceScopedForResourceWithResourceResponse instantiates a new ScopedforresourcewithresourceScopedForResourceWithResourceResponse and sets the default values.
func NewScopedforresourcewithresourceScopedForResourceWithResourceResponse()(*ScopedforresourcewithresourceScopedForResourceWithResourceResponse) {
    m := &ScopedforresourcewithresourceScopedForResourceWithResourceResponse{
        ScopedforresourcewithresourceScopedForResourceWithResourceGetResponse: *NewScopedforresourcewithresourceScopedForResourceWithResourceGetResponse(),
    }
    return m
}
// CreateScopedforresourcewithresourceScopedForResourceWithResourceResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateScopedforresourcewithresourceScopedForResourceWithResourceResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewScopedforresourcewithresourceScopedForResourceWithResourceResponse(), nil
}
// Deprecated: This class is obsolete. Use ScopedforresourcewithresourceScopedForResourceWithResourceGetResponseable instead.
type ScopedforresourcewithresourceScopedForResourceWithResourceResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    ScopedforresourcewithresourceScopedForResourceWithResourceGetResponseable
}
