package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use TemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesPostResponseable instead.
type TemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesResponse struct {
    TemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesPostResponse
}
// NewTemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesResponse instantiates a new TemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesResponse and sets the default values.
func NewTemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesResponse()(*TemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesResponse) {
    m := &TemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesResponse{
        TemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesPostResponse: *NewTemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesPostResponse(),
    }
    return m
}
// CreateTemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesResponse(), nil
}
// Deprecated: This class is obsolete. Use TemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesPostResponseable instead.
type TemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    TemplatesItemMigratabletoImportoffice365deviceconfigurationpoliciesImportOffice365DeviceConfigurationPoliciesPostResponseable
}
