package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use VirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsGetResponseable instead.
type VirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsResponse struct {
    VirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsGetResponse
}
// NewVirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsResponse instantiates a new VirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsResponse and sets the default values.
func NewVirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsResponse()(*VirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsResponse) {
    m := &VirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsResponse{
        VirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsGetResponse: *NewVirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsGetResponse(),
    }
    return m
}
// CreateVirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewVirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsResponse(), nil
}
// Deprecated: This class is obsolete. Use VirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsGetResponseable instead.
type VirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    VirtualendpointCloudpcsItemGetsupportedcloudpcremoteactionsGetSupportedCloudPcRemoteActionsGetResponseable
}
