package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// VirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponse 
// Deprecated: This class is obsolete. Use getSupportedCloudPcRemoteActionsGetResponse instead.
type VirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponse struct {
    VirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsGetResponse
}
// NewVirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponse instantiates a new VirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponse and sets the default values.
func NewVirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponse()(*VirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponse) {
    m := &VirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponse{
        VirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsGetResponse: *NewVirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsGetResponse(),
    }
    return m
}
// CreateVirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateVirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewVirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponse(), nil
}
// VirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponseable 
// Deprecated: This class is obsolete. Use getSupportedCloudPcRemoteActionsGetResponse instead.
type VirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    VirtualEndpointCloudPCsItemGetSupportedCloudPcRemoteActionsGetResponseable
}
