package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use VirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponseable instead.
type VirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse struct {
    VirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponse
}
// NewVirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse instantiates a new VirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse and sets the default values.
func NewVirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse()(*VirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse) {
    m := &VirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse{
        VirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponse: *NewVirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponse(),
    }
    return m
}
// CreateVirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewVirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponse(), nil
}
// Deprecated: This class is obsolete. Use VirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponseable instead.
type VirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    VirtualendpointCloudpcsGetprovisionedcloudpcswithgroupidwithserviceplanidGetProvisionedCloudPCsWithGroupIdWithServicePlanIdGetResponseable
}
