package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use VirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsGetResponseable instead.
type VirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsResponse struct {
    VirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsGetResponse
}
// NewVirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsResponse instantiates a new VirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsResponse and sets the default values.
func NewVirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsResponse()(*VirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsResponse) {
    m := &VirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsResponse{
        VirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsGetResponse: *NewVirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsGetResponse(),
    }
    return m
}
// CreateVirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewVirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsResponse(), nil
}
// Deprecated: This class is obsolete. Use VirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsGetResponseable instead.
type VirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    VirtualendpointRetrievescopedpermissionsRetrieveScopedPermissionsGetResponseable
}
