package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use WindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksPostResponseable instead.
type WindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksResponse struct {
    WindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksPostResponse
}
// NewWindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksResponse instantiates a new WindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksResponse and sets the default values.
func NewWindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksResponse()(*WindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksResponse) {
    m := &WindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksResponse{
        WindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksPostResponse: *NewWindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksPostResponse(),
    }
    return m
}
// CreateWindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateWindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewWindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksResponse(), nil
}
// Deprecated: This class is obsolete. Use WindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksPostResponseable instead.
type WindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    WindowsautopilotdeploymentprofilesHaspayloadlinksHasPayloadLinksPostResponseable
}
