package deviceappmanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use IoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksPostResponseable instead.
type IoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksResponse struct {
    IoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksPostResponse
}
// NewIoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksResponse instantiates a new IoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksResponse and sets the default values.
func NewIoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksResponse()(*IoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksResponse) {
    m := &IoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksResponse{
        IoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksPostResponse: *NewIoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksPostResponse(),
    }
    return m
}
// CreateIoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewIoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksResponse(), nil
}
// Deprecated: This class is obsolete. Use IoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksPostResponseable instead.
type IoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksResponseable interface {
    IoslobappprovisioningconfigurationsHaspayloadlinksHasPayloadLinksPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
