package deviceappmanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use VpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdGetResponseable instead.
type VpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdResponse struct {
    VpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdGetResponse
}
// NewVpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdResponse instantiates a new VpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdResponse and sets the default values.
func NewVpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdResponse()(*VpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdResponse) {
    m := &VpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdResponse{
        VpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdGetResponse: *NewVpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdGetResponse(),
    }
    return m
}
// CreateVpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewVpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdResponse(), nil
}
// Deprecated: This class is obsolete. Use VpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdGetResponseable instead.
type VpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    VpptokensGetlicensesforappwithbundleidGetLicensesForAppWithBundleIdGetResponseable
}
