package policies

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponse 
// Deprecated: This class is obsolete. Use findByMethodModeWithAuthenticationMethodModesGetResponse instead.
type AuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponse struct {
    AuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesGetResponse
}
// NewAuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponse instantiates a new AuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponse and sets the default values.
func NewAuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponse()(*AuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponse) {
    m := &AuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponse{
        AuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesGetResponse: *NewAuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesGetResponse(),
    }
    return m
}
// CreateAuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateAuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponse(), nil
}
// AuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponseable 
// Deprecated: This class is obsolete. Use findByMethodModeWithAuthenticationMethodModesGetResponse instead.
type AuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesResponseable interface {
    AuthenticationStrengthPoliciesFindByMethodModeWithAuthenticationMethodModesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
