package policies

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilder builds and executes requests for operations under \policies\mobileAppManagementPolicies\{mobilityManagementPolicy-id}\includedGroups\{group-id}
type MobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewMobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilderInternal instantiates a new MobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilder and sets the default values.
func NewMobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilder) {
    m := &MobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/policies/mobileAppManagementPolicies/{mobilityManagementPolicy%2Did}/includedGroups/{group%2Did}", pathParameters),
    }
    return m
}
// NewMobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilder instantiates a new MobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilder and sets the default values.
func NewMobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewMobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Ref provides operations to manage the collection of policyRoot entities.
// returns a *MobileappmanagementpoliciesItemIncludedgroupsItemRefRequestBuilder when successful
func (m *MobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilder) Ref()(*MobileappmanagementpoliciesItemIncludedgroupsItemRefRequestBuilder) {
    return NewMobileappmanagementpoliciesItemIncludedgroupsItemRefRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ServiceProvisioningErrors the serviceProvisioningErrors property
// returns a *MobileappmanagementpoliciesItemIncludedgroupsItemServiceprovisioningerrorsServiceProvisioningErrorsRequestBuilder when successful
func (m *MobileappmanagementpoliciesItemIncludedgroupsGroupItemRequestBuilder) ServiceProvisioningErrors()(*MobileappmanagementpoliciesItemIncludedgroupsItemServiceprovisioningerrorsServiceProvisioningErrorsRequestBuilder) {
    return NewMobileappmanagementpoliciesItemIncludedgroupsItemServiceprovisioningerrorsServiceProvisioningErrorsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
