package security
import (
    "strings"
    "errors"
)
// 
type ServiceSource int

const (
    UNKNOWN_SERVICESOURCE ServiceSource = iota
    MICROSOFTDEFENDERFORENDPOINT_SERVICESOURCE
    MICROSOFTDEFENDERFORIDENTITY_SERVICESOURCE
    MICROSOFTDEFENDERFORCLOUDAPPS_SERVICESOURCE
    MICROSOFTDEFENDERFOROFFICE365_SERVICESOURCE
    MICROSOFT365DEFENDER_SERVICESOURCE
    AADIDENTITYPROTECTION_SERVICESOURCE
    MICROSOFTAPPGOVERNANCE_SERVICESOURCE
    DATALOSSPREVENTION_SERVICESOURCE
    UNKNOWNFUTUREVALUE_SERVICESOURCE
)

func (i ServiceSource) String() string {
    return []string{"UNKNOWN", "MICROSOFTDEFENDERFORENDPOINT", "MICROSOFTDEFENDERFORIDENTITY", "MICROSOFTDEFENDERFORCLOUDAPPS", "MICROSOFTDEFENDERFOROFFICE365", "MICROSOFT365DEFENDER", "AADIDENTITYPROTECTION", "MICROSOFTAPPGOVERNANCE", "DATALOSSPREVENTION", "UNKNOWNFUTUREVALUE"}[i]
}
func ParseServiceSource(v string) (interface{}, error) {
    result := UNKNOWN_SERVICESOURCE
    switch strings.ToUpper(v) {
        case "UNKNOWN":
            result = UNKNOWN_SERVICESOURCE
        case "MICROSOFTDEFENDERFORENDPOINT":
            result = MICROSOFTDEFENDERFORENDPOINT_SERVICESOURCE
        case "MICROSOFTDEFENDERFORIDENTITY":
            result = MICROSOFTDEFENDERFORIDENTITY_SERVICESOURCE
        case "MICROSOFTDEFENDERFORCLOUDAPPS":
            result = MICROSOFTDEFENDERFORCLOUDAPPS_SERVICESOURCE
        case "MICROSOFTDEFENDERFOROFFICE365":
            result = MICROSOFTDEFENDERFOROFFICE365_SERVICESOURCE
        case "MICROSOFT365DEFENDER":
            result = MICROSOFT365DEFENDER_SERVICESOURCE
        case "AADIDENTITYPROTECTION":
            result = AADIDENTITYPROTECTION_SERVICESOURCE
        case "MICROSOFTAPPGOVERNANCE":
            result = MICROSOFTAPPGOVERNANCE_SERVICESOURCE
        case "DATALOSSPREVENTION":
            result = DATALOSSPREVENTION_SERVICESOURCE
        case "UNKNOWNFUTUREVALUE":
            result = UNKNOWNFUTUREVALUE_SERVICESOURCE
        default:
            return 0, errors.New("Unknown ServiceSource value: " + v)
    }
    return &result, nil
}
func SerializeServiceSource(values []ServiceSource) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
