// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package casemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Activity struct {
    CaseManagementEntity
}
// NewActivity instantiates a new Activity and sets the default values.
func NewActivity()(*Activity) {
    m := &Activity{
        CaseManagementEntity: *NewCaseManagementEntity(),
    }
    odataTypeValue := "#microsoft.graph.security.caseManagement.activity"
    m.SetOdataType(&odataTypeValue)
    return m
}
// CreateActivityFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateActivityFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    if parseNode != nil {
        mappingValueNode, err := parseNode.GetChildNode("@odata.type")
        if err != nil {
            return nil, err
        }
        if mappingValueNode != nil {
            mappingValue, err := mappingValueNode.GetStringValue()
            if err != nil {
                return nil, err
            }
            if mappingValue != nil {
                switch *mappingValue {
                    case "#microsoft.graph.security.caseManagement.auditLog":
                        return NewAuditLog(), nil
                    case "#microsoft.graph.security.caseManagement.comment":
                        return NewComment(), nil
                }
            }
        }
    }
    return NewActivity(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Activity) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.CaseManagementEntity.GetFieldDeserializers()
    return res
}
// Serialize serializes information the current object
func (m *Activity) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.CaseManagementEntity.Serialize(writer)
    if err != nil {
        return err
    }
    return nil
}
type Activityable interface {
    CaseManagementEntityable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
