// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package casemanagement
type TaskStatus int

const (
    NOTSET_TASKSTATUS TaskStatus = iota
    NEW_TASKSTATUS
    INPROGRESS_TASKSTATUS
    FAILED_TASKSTATUS
    PARTIALLYCOMPLETED_TASKSTATUS
    SKIPPED_TASKSTATUS
    COMPLETED_TASKSTATUS
    UNKNOWNFUTUREVALUE_TASKSTATUS
)

func (i TaskStatus) String() string {
    return []string{"notSet", "new", "inProgress", "failed", "partiallyCompleted", "skipped", "completed", "unknownFutureValue"}[i]
}
func ParseTaskStatus(v string) (any, error) {
    result := NOTSET_TASKSTATUS
    switch v {
        case "notSet":
            result = NOTSET_TASKSTATUS
        case "new":
            result = NEW_TASKSTATUS
        case "inProgress":
            result = INPROGRESS_TASKSTATUS
        case "failed":
            result = FAILED_TASKSTATUS
        case "partiallyCompleted":
            result = PARTIALLYCOMPLETED_TASKSTATUS
        case "skipped":
            result = SKIPPED_TASKSTATUS
        case "completed":
            result = COMPLETED_TASKSTATUS
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_TASKSTATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeTaskStatus(values []TaskStatus) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i TaskStatus) isMultiValue() bool {
    return false
}
