package onpremisespublishingprofiles

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilder builds and executes requests for operations under \onPremisesPublishingProfiles\{onPremisesPublishingProfile-id}\agentGroups\{onPremisesAgentGroup-id}\publishedResources\{publishedResource-id}\agentGroups\{onPremisesAgentGroup-id1}
type ItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilderInternal instantiates a new ItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilder and sets the default values.
func NewItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilder) {
    m := &ItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/onPremisesPublishingProfiles/{onPremisesPublishingProfile%2Did}/agentGroups/{onPremisesAgentGroup%2Did}/publishedResources/{publishedResource%2Did}/agentGroups/{onPremisesAgentGroup%2Did1}", pathParameters),
    }
    return m
}
// NewItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilder instantiates a new ItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilder and sets the default values.
func NewItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Ref provides operations to manage the collection of onPremisesPublishingProfile entities.
// returns a *ItemAgentgroupsItemPublishedresourcesItemAgentgroupsItemRefRequestBuilder when successful
func (m *ItemAgentgroupsItemPublishedresourcesItemAgentgroupsOnPremisesAgentGroupItemRequestBuilder) Ref()(*ItemAgentgroupsItemPublishedresourcesItemAgentgroupsItemRefRequestBuilder) {
    return NewItemAgentgroupsItemPublishedresourcesItemAgentgroupsItemRefRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
