// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CloudPcAgentPool struct {
    CloudPcPool
}
// NewCloudPcAgentPool instantiates a new CloudPcAgentPool and sets the default values.
func NewCloudPcAgentPool()(*CloudPcAgentPool) {
    m := &CloudPcAgentPool{
        CloudPcPool: *NewCloudPcPool(),
    }
    odataTypeValue := "#microsoft.graph.cloudPcAgentPool"
    m.SetOdataType(&odataTypeValue)
    return m
}
// CreateCloudPcAgentPoolFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCloudPcAgentPoolFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCloudPcAgentPool(), nil
}
// GetBillingConfiguration gets the billingConfiguration property value. The billingConfiguration property
// returns a CloudPcAgentPoolBillingConfigurationable when successful
func (m *CloudPcAgentPool) GetBillingConfiguration()(CloudPcAgentPoolBillingConfigurationable) {
    val, err := m.GetBackingStore().Get("billingConfiguration")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(CloudPcAgentPoolBillingConfigurationable)
    }
    return nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CloudPcAgentPool) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.CloudPcPool.GetFieldDeserializers()
    res["billingConfiguration"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCloudPcAgentPoolBillingConfigurationFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBillingConfiguration(val.(CloudPcAgentPoolBillingConfigurationable))
        }
        return nil
    }
    res["poolUrl"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPoolUrl(val)
        }
        return nil
    }
    res["scalingPolicy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCloudPcAgentPoolScalingPolicyFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetScalingPolicy(val.(CloudPcAgentPoolScalingPolicyable))
        }
        return nil
    }
    res["sessionUsage"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCloudPcAgentPoolSessionUsageFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSessionUsage(val.(CloudPcAgentPoolSessionUsageable))
        }
        return nil
    }
    return res
}
// GetPoolUrl gets the poolUrl property value. The poolUrl property
// returns a *string when successful
func (m *CloudPcAgentPool) GetPoolUrl()(*string) {
    val, err := m.GetBackingStore().Get("poolUrl")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetScalingPolicy gets the scalingPolicy property value. The scalingPolicy property
// returns a CloudPcAgentPoolScalingPolicyable when successful
func (m *CloudPcAgentPool) GetScalingPolicy()(CloudPcAgentPoolScalingPolicyable) {
    val, err := m.GetBackingStore().Get("scalingPolicy")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(CloudPcAgentPoolScalingPolicyable)
    }
    return nil
}
// GetSessionUsage gets the sessionUsage property value. The sessionUsage property
// returns a CloudPcAgentPoolSessionUsageable when successful
func (m *CloudPcAgentPool) GetSessionUsage()(CloudPcAgentPoolSessionUsageable) {
    val, err := m.GetBackingStore().Get("sessionUsage")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(CloudPcAgentPoolSessionUsageable)
    }
    return nil
}
// Serialize serializes information the current object
func (m *CloudPcAgentPool) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.CloudPcPool.Serialize(writer)
    if err != nil {
        return err
    }
    {
        err = writer.WriteObjectValue("billingConfiguration", m.GetBillingConfiguration())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("poolUrl", m.GetPoolUrl())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteObjectValue("scalingPolicy", m.GetScalingPolicy())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteObjectValue("sessionUsage", m.GetSessionUsage())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetBillingConfiguration sets the billingConfiguration property value. The billingConfiguration property
func (m *CloudPcAgentPool) SetBillingConfiguration(value CloudPcAgentPoolBillingConfigurationable)() {
    err := m.GetBackingStore().Set("billingConfiguration", value)
    if err != nil {
        panic(err)
    }
}
// SetPoolUrl sets the poolUrl property value. The poolUrl property
func (m *CloudPcAgentPool) SetPoolUrl(value *string)() {
    err := m.GetBackingStore().Set("poolUrl", value)
    if err != nil {
        panic(err)
    }
}
// SetScalingPolicy sets the scalingPolicy property value. The scalingPolicy property
func (m *CloudPcAgentPool) SetScalingPolicy(value CloudPcAgentPoolScalingPolicyable)() {
    err := m.GetBackingStore().Set("scalingPolicy", value)
    if err != nil {
        panic(err)
    }
}
// SetSessionUsage sets the sessionUsage property value. The sessionUsage property
func (m *CloudPcAgentPool) SetSessionUsage(value CloudPcAgentPoolSessionUsageable)() {
    err := m.GetBackingStore().Set("sessionUsage", value)
    if err != nil {
        panic(err)
    }
}
type CloudPcAgentPoolable interface {
    CloudPcPoolable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetBillingConfiguration()(CloudPcAgentPoolBillingConfigurationable)
    GetPoolUrl()(*string)
    GetScalingPolicy()(CloudPcAgentPoolScalingPolicyable)
    GetSessionUsage()(CloudPcAgentPoolSessionUsageable)
    SetBillingConfiguration(value CloudPcAgentPoolBillingConfigurationable)()
    SetPoolUrl(value *string)()
    SetScalingPolicy(value CloudPcAgentPoolScalingPolicyable)()
    SetSessionUsage(value CloudPcAgentPoolSessionUsageable)()
}
