// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// A list of possible status states for a sync infrastructure component or policy during a device sync operation.
type SyncComponentStatus int

const (
    // Default. The component has not yet started reporting status. This is a schema default and will not typically appear in responses, as components only appear once they begin executing.
    NONE_SYNCCOMPONENTSTATUS SyncComponentStatus = iota
    // Indicates the component is currently executing. For infrastructure components (PNSv1, DCI, SCGW), this means the notification or check-in is in flight. For policies, this means the policy is being applied to the device.
    INPROGRESS_SYNCCOMPONENTSTATUS
    // Indicates the component completed successfully. The component has finished its work and reported a successful outcome.
    SUCCESS_SYNCCOMPONENTSTATUS
    // Indicates the stage encountered an error. When this value is set, the moreInfo property on the syncComponent will contain additional diagnostic details about the failure.
    FAILURE_SYNCCOMPONENTSTATUS
    // Indicates the stage completed but not all items succeeded. For example, some policies applied successfully while others failed. The moreInfo property may contain details on the partial outcome.
    PARTIALSUCCESS_SYNCCOMPONENTSTATUS
    // Evolvable enumeration sentinel value. Do not use.
    UNKNOWNFUTUREVALUE_SYNCCOMPONENTSTATUS
)

func (i SyncComponentStatus) String() string {
    return []string{"none", "inProgress", "success", "failure", "partialSuccess", "unknownFutureValue"}[i]
}
func ParseSyncComponentStatus(v string) (any, error) {
    result := NONE_SYNCCOMPONENTSTATUS
    switch v {
        case "none":
            result = NONE_SYNCCOMPONENTSTATUS
        case "inProgress":
            result = INPROGRESS_SYNCCOMPONENTSTATUS
        case "success":
            result = SUCCESS_SYNCCOMPONENTSTATUS
        case "failure":
            result = FAILURE_SYNCCOMPONENTSTATUS
        case "partialSuccess":
            result = PARTIALSUCCESS_SYNCCOMPONENTSTATUS
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_SYNCCOMPONENTSTATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeSyncComponentStatus(values []SyncComponentStatus) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i SyncComponentStatus) isMultiValue() bool {
    return false
}
